import { IGuestList, ISingleGuestInvitationList } from "./type";

export const GuestListData: IGuestList[] = [
  {
    orderId: "A12345",
    unit: "02",
    name: "Mac s Far",
    organization: "Alchemy Project",
    date: "2025-01-01T12:00:00Z",
    deliveryAddress: "isticaque@tixbox.com",
    status: "Issued",
    transactionSummary: {
      paymentMethod: "Credit Card",
      totalValue: "200.00",
      promoCode: "NEWYEAR25",
      discount: 10,
      grandTotal: "180.00",
      issuedBy: "Admin",
    },
    orderDetails: {
      tickets: [
        {
          quantity: 2,
          costPerTicket: "100.00",
          name: "VIP Concert Ticket",
          totalCost: "200.00",
        },
      ],
      processFee: "10.00",
      serviceCharge: "5.00",
      netTotal: "190.00",
      discount: "10.00",
      discountValue: "20.00",
      discountType: "Promo Code",
      vat: 5,
      vatValue: "7.87",
      grandTotal: "180.00",
    },
  },
  {
    orderId: "B67890",
    unit: "01",
    name: "John Doe",
    organization: "Event Corp",
    date: "2025-02-15T15:30:00Z",
    deliveryAddress: "john.doe@example.com",
    status: "Cancelled",
    transactionSummary: {
      paymentMethod: "PayPal",
      totalValue: "150.00",
      promoCode: "WINTER10",
      discount: 10,
      grandTotal: "135.00",
      issuedBy: "Admin",
    },
    orderDetails: {
      tickets: [
        {
          quantity: 1,
          costPerTicket: "150.00",
          name: "Standard Concert Ticket",
          totalCost: "150.00",
        },
      ],
      processFee: "5.00",
      serviceCharge: "2.50",
      netTotal: "147.50",
      discount: "12.50",
      discountType: "Promo Code",
      vat: 5,
      vatValue: "13.87",
      grandTotal: "135.00",
      discountValue: "15.00",
    },
  },
  {
    orderId: "C54321",
    unit: "03",
    name: "Jane Smith",
    organization: "MusicFest Inc.",
    date: "2025-03-10T20:00:00Z",
    deliveryAddress: "jane.smith@example.com",
    status: "Used",
    transactionSummary: {
      paymentMethod: "ApplePay",
      totalValue: "300.00",
      promoCode: "SPRING20",
      discount: 15,
      grandTotal: "255.00",
      issuedBy: "Admin",
    },
    orderDetails: {
      tickets: [
        {
          quantity: 3,
          costPerTicket: "100.00",
          name: "Premium Concert Ticket",
          totalCost: "300.00",
        },
      ],
      processFee: "15.00",
      serviceCharge: "7.50",
      netTotal: "292.50",
      discount: "37.50",
      discountType: "Promo Code",
      discountValue: "45.00",
      vat: 5,
      grandTotal: "255.00",
      vatValue: "13.87",
    },
  },
];

export const SingleGuestInvitationList: ISingleGuestInvitationList[] = [
  {
    ticket: "Bronze Ticket",
    availability: "420 from 1500",
    availabilityPercentage: 30.2,
    count: 4,
    amount: 69.0,
    ageLimit: "above 2 years of age",
    inclusions: [
      "Access to Gold Area",
      "Free Parking",
      "2 Free Drinks",
      "Access to General Food Court",
      "Access to Gold Area",
      "Free Parking",
      "2 Free Drinks",
      "Access to General Food Court",
    ],
  },
  {
    ticket: "Silver Ticket",
    availability: "420 from 1500",
    availabilityPercentage: 30.2,
    count: 4,
    amount: 69.0,
    ageLimit: "above 2 years of age",
    inclusions: [
      "Access to Gold Area",
      "Free Parking",
      "2 Free Drinks",
      "Access to General Food Court",
      "Access to Gold Area",
      "Free Parking",
      "2 Free Drinks",
      "Access to General Food Court",
    ],
  },
  {
    ticket: "Gold Ticket",
    availability: "420 from 1500",
    availabilityPercentage: 30.2,
    count: 4,
    amount: 69.0,
    ageLimit: "above 2 years of age",
    inclusions: [
      "Access to Gold Area",
      "Free Parking",
      "2 Free Drinks",
      "Access to General Food Court",
      "Access to Gold Area",
      "Free Parking",
      "2 Free Drinks",
      "Access to General Food Court",
    ],
  },
  {
    ticket: "Platinum Ticket",
    availability: "420 from 1500",
    availabilityPercentage: 30.2,
    count: 4,
    amount: 69.0,
    ageLimit: "above 2 years of age",
    inclusions: [
      "Access to Gold Area",
      "Free Parking",
      "2 Free Drinks",
      "Access to General Food Court",
      "Access to Gold Area",
      "Free Parking",
      "2 Free Drinks",
      "Access to General Food Court",
    ],
  },
  {
    ticket: "VIP Ticket",
    availability: "420 from 1500",
    availabilityPercentage: 30.2,
    count: 4,
    amount: 69.0,
    ageLimit: "above 2 years of age",
    inclusions: [
      "Access to Gold Area",
      "Free Parking",
      "2 Free Drinks",
      "Access to General Food Court",
      "Access to Gold Area",
      "Free Parking",
      "2 Free Drinks",
      "Access to General Food Court",
    ],
  },
  {
    ticket: "VIP Lounge",
    availability: "420 from 1500",
    availabilityPercentage: 30.2,
    count: 4,
    amount: 69.0,
    ageLimit: "above 2 years of age",
    inclusions: [
      "Access to Gold Area",
      "Free Parking",
      "2 Free Drinks",
      "Access to General Food Court",
      "Access to Gold Area",
      "Free Parking",
      "2 Free Drinks",
      "Access to General Food Court",
    ],
  },
];
export const SingleGuestInvitationServiceList: ISingleGuestInvitationList[] = [
  {
    ticket: "Bronze Ticket",
    availability: "420 from 1500",
    availabilityPercentage: 50.2,
    count: 2,
    amount: 69.0,
    ageLimit: "above 2 years of age",
    inclusions: [
      "Access to Gold Area",
      "Free Parking",
      "2 Free Drinks",
      "Access to General Food Court",
      "Access to Gold Area",
      "Free Parking",
      "2 Free Drinks",
      "Access to General Food Court",
    ],
  },
  {
    ticket: "Silver Ticket",
    availability: "420 from 1500",
    availabilityPercentage: 30.9,
    count: 4,
    amount: 69.0,
    ageLimit: "above 2 years of age",
    inclusions: [
      "Access to Gold Area",
      "Free Parking",
      "2 Free Drinks",
      "Access to General Food Court",
      "Access to Gold Area",
      "Free Parking",
      "2 Free Drinks",
      "Access to General Food Court",
    ],
  },
  {
    ticket: "Gold Ticket",
    availability: "420 from 1500",
    availabilityPercentage: 10.2,
    count: 9,
    amount: 69.0,
    ageLimit: "above 2 years of age",
    inclusions: [
      "Access to Gold Area",
      "Free Parking",
      "2 Free Drinks",
      "Access to General Food Court",
      "Access to Gold Area",
      "Free Parking",
      "2 Free Drinks",
      "Access to General Food Court",
    ],
  },
  {
    ticket: "Platinum Ticket",
    availability: "420 from 1500",
    availabilityPercentage: 39.2,
    count: 4,
    amount: 69.0,
    ageLimit: "above 2 years of age",
    inclusions: [
      "Access to Gold Area",
      "Free Parking",
      "2 Free Drinks",
      "Access to General Food Court",
      "Access to Gold Area",
      "Free Parking",
      "2 Free Drinks",
      "Access to General Food Court",
    ],
  },
];
export const SingleGuestInvitationAddOnsList: ISingleGuestInvitationList[] = [
  {
    ticket: "Bronze Ticket",
    availability: "420 from 1500",
    availabilityPercentage: 30.2,
    count: 2,
    amount: 69.0,
    ageLimit: "above 2 years of age",
    inclusions: [
      "Access to Gold Area",
      "Free Parking",
      "2 Free Drinks",
      "Access to General Food Court",
      "Access to Gold Area",
      "Free Parking",
      "2 Free Drinks",
      "Access to General Food Court",
    ],
  },
  {
    ticket: "Silver Ticket",
    availability: "420 from 1500",
    availabilityPercentage: 38.9,
    count: 4,
    amount: 69.0,
    ageLimit: "above 2 years of age",
    inclusions: [
      "Access to Gold Area",
      "Free Parking",
      "2 Free Drinks",
      "Access to General Food Court",
      "Access to Gold Area",
      "Free Parking",
      "2 Free Drinks",
      "Access to General Food Court",
    ],
  },
  {
    ticket: "Gold Ticket",
    availability: "420 from 1500",
    availabilityPercentage: 19.2,
    count: 1,
    amount: 69.0,
    ageLimit: "above 2 years of age",
    inclusions: [
      "Access to Gold Area",
      "Free Parking",
      "2 Free Drinks",
      "Access to General Food Court",
      "Access to Gold Area",
      "Free Parking",
      "2 Free Drinks",
      "Access to General Food Court",
    ],
  },
  {
    ticket: "Platinum Ticket",
    availability: "420 from 1500",
    availabilityPercentage: 19.2,
    count: 1,
    amount: 69.0,
    ageLimit: "above 2 years of age",
    inclusions: [
      "Access to Gold Area",
      "Free Parking",
      "2 Free Drinks",
      "Access to General Food Court",
      "Access to Gold Area",
      "Free Parking",
      "2 Free Drinks",
      "Access to General Food Court",
    ],
  },
];
export const SingleGuestInvitationMerchandiseList: ISingleGuestInvitationList[] =
  [
    {
      ticket: "Bronze Ticket",
      availability: "420 from 1500",
      availabilityPercentage: 50.2,
      count: 2,
      amount: 69.0,
      ageLimit: "above 2 years of age",
      inclusions: [
        "Access to Gold Area",
        "Free Parking",
        "2 Free Drinks",
        "Access to General Food Court",
        "Access to Gold Area",
        "Free Parking",
        "2 Free Drinks",
        "Access to General Food Court",
      ],
    },
    {
      ticket: "Silver Ticket",
      availability: "420 from 1500",
      availabilityPercentage: 30.9,
      count: 4,
      amount: 69.0,
      ageLimit: "above 2 years of age",
      inclusions: [
        "Access to Gold Area",
        "Free Parking",
        "2 Free Drinks",
        "Access to General Food Court",
        "Access to Gold Area",
        "Free Parking",
        "2 Free Drinks",
        "Access to General Food Court",
      ],
    },
    {
      ticket: "Gold Ticket",
      availability: "420 from 1500",
      availabilityPercentage: 10.2,
      count: 9,
      amount: 69.0,
      ageLimit: "above 2 years of age",
      inclusions: [
        "Access to Gold Area",
        "Free Parking",
        "2 Free Drinks",
        "Access to General Food Court",
        "Access to Gold Area",
        "Free Parking",
        "2 Free Drinks",
        "Access to General Food Court",
      ],
    },
    {
      ticket: "Platinum Ticket",
      availability: "420 from 1500",
      availabilityPercentage: 39.2,
      count: 4,
      amount: 69.0,
      ageLimit: "above 2 years of age",
      inclusions: [
        "Access to Gold Area",
        "Free Parking",
        "2 Free Drinks",
        "Access to General Food Court",
        "Access to Gold Area",
        "Free Parking",
        "2 Free Drinks",
        "Access to General Food Court",
      ],
    },
  ];
export const SingleGuestInvitationFBList: ISingleGuestInvitationList[] = [
  {
    ticket: "Bronze Ticket",
    availability: "420 from 1500",
    availabilityPercentage: 88.2,
    count: 7,
    amount: 69.0,
    ageLimit: "above 2 years of age",
    inclusions: [
      "Access to Gold Area",
      "Free Parking",
      "2 Free Drinks",
      "Access to General Food Court",
      "Access to Gold Area",
      "Free Parking",
      "2 Free Drinks",
      "Access to General Food Court",
    ],
  },
  {
    ticket: "Silver Ticket",
    availability: "420 from 1500",
    availabilityPercentage: 33.9,
    count: 4,
    amount: 69.0,
    ageLimit: "above 2 years of age",
    inclusions: [
      "Access to Gold Area",
      "Free Parking",
      "2 Free Drinks",
      "Access to General Food Court",
      "Access to Gold Area",
      "Free Parking",
      "2 Free Drinks",
      "Access to General Food Court",
    ],
  },
  {
    ticket: "Gold Ticket",
    availability: "420 from 1500",
    availabilityPercentage: 10.2,
    count: 8,
    amount: 69.0,
    ageLimit: "above 2 years of age",
    inclusions: [
      "Access to Gold Area",
      "Free Parking",
      "2 Free Drinks",
      "Access to General Food Court",
      "Access to Gold Area",
      "Free Parking",
      "2 Free Drinks",
      "Access to General Food Court",
    ],
  },
  {
    ticket: "Platinum Ticket",
    availability: "420 from 1500",
    availabilityPercentage: 39.2,
    count: 4,
    amount: 69.0,
    ageLimit: "above 2 years of age",
    inclusions: [
      "Access to Gold Area",
      "Free Parking",
      "2 Free Drinks",
      "Access to General Food Court",
      "Access to Gold Area",
      "Free Parking",
      "2 Free Drinks",
      "Access to General Food Court",
    ],
  },
];
