import { boolean } from "yup";

// export const MENUITEMS = [
//   {
//     menutitle: "MAIN",
//     Items: [
//       {
//         path: `${import.meta.env.BASE_URL}dashboard`,
//         icon: "fe fe-home",
//         type: "link",
//         active: false,
//         selected: false,
//         title: "Dashboard",
//       },
//     ],
//   },
//   {
//     menutitle: "UI KIT",

//     Items: [
//       {
//         title: "Apps",
//         icon: "fe fe-slack",
//         type: "sub",
//         Name: "",
//         Names: "",
//         active: false,
//         selected: false,
//         children: [
//           {
//             path: `${import.meta.env.BASE_URL}apps/carddesigns`,
//             type: "link",
//             active: false,
//             selected: false,
//             title: "Cards-design",
//           },
//           {
//             path: `${import.meta.env.BASE_URL}apps/chat`,
//             type: "link",
//             active: false,
//             selected: false,
//             title: "Chat",
//           },
//           {
//             path: `${import.meta.env.BASE_URL}apps/charts`,
//             type: "link",
//             active: false,
//             selected: false,
//             title: "Charts",
//           },
//           {
//             path: `${import.meta.env.BASE_URL}apps/scrollbar`,
//             type: "link",
//             active: false,
//             selected: false,
//             title: "Content-Scrollbar",
//           },
//           {
//             path: `${import.meta.env.BASE_URL}apps/counter`,
//             type: "link",
//             active: false,
//             selected: false,
//             title: "Counters",
//           },
//           {
//             path: `${import.meta.env.BASE_URL}apps/cryptocurrencies`,
//             type: "link",
//             active: false,
//             selected: false,
//             title: "Crypto-Currencies",
//           },
//           {
//             path: `${import.meta.env.BASE_URL}apps/defaultcalender`,
//             type: "link",
//             active: false,
//             selected: false,
//             title: "Default-Calender",
//           },
//           {
//             path: `${import.meta.env.BASE_URL}apps/footer`,
//             type: "link",
//             active: false,
//             selected: false,
//             title: "Footers",
//           },
//           {
//             path: `${import.meta.env.BASE_URL}apps/fullcalender`,
//             type: "link",
//             active: false,
//             selected: false,
//             title: "Full-Calender",
//           },
//           {
//             path: `${import.meta.env.BASE_URL}apps/loader`,
//             type: "link",
//             active: false,
//             selected: false,
//             title: "Loaders",
//           },
//           {
//             path: `${import.meta.env.BASE_URL}apps/notification`,
//             type: "link",
//             active: false,
//             selected: false,
//             title: "Notifications",
//           },
//           {
//             path: `${import.meta.env.BASE_URL}apps/rangeslider`,
//             type: "link",
//             active: false,
//             selected: false,
//             title: "Range-slider",
//           },
//           {
//             path: `${import.meta.env.BASE_URL}apps/rating`,
//             type: "link",
//             active: false,
//             selected: false,
//             title: "Rating",
//           },
//           {
//             path: `${import.meta.env.BASE_URL}apps/search`,
//             type: "link",
//             active: false,
//             selected: false,
//             title: "Search",
//           },
//           {
//             path: `${import.meta.env.BASE_URL}apps/sweet`,
//             type: "link",
//             active: false,
//             selected: false,
//             title: "Sweet-alerts",
//           },
//           {
//             path: `${import.meta.env.BASE_URL}apps/timeline`,
//             type: "link",
//             active: false,
//             selected: false,
//             title: "Timeline",
//           },
//           {
//             path: `${import.meta.env.BASE_URL}apps/treeview`,
//             type: "link",
//             active: false,
//             selected: false,
//             title: "TreeView",
//           },
//           {
//             path: `${import.meta.env.BASE_URL}apps/userlist`,
//             type: "link",
//             active: false,
//             selected: false,
//             title: "User-list",
//           },
//           {
//             path: `${import.meta.env.BASE_URL}apps/widgets`,
//             type: "link",
//             active: false,
//             selected: false,
//             title: "Widgets",
//           },
//         ],
//       },
//       {
//         title: "Bootstrap",
//         icon: "fe fe-package",
//         type: "sub",
//         active: false,
//         selected: false,
//         Names: "mega-slide-menu",
//         Name: "mega-menu",
//         children: [
//           {
//             path: `${import.meta.env.BASE_URL}bootstrap/accordian`,
//             type: "link",
//             active: false,
//             selected: false,
//             title: "Accordions",
//           },
//           {
//             path: `${import.meta.env.BASE_URL}bootstrap/bootstrapalerts`,
//             type: "link",
//             active: false,
//             selected: false,
//             title: "Alerts",
//           },
//           {
//             path: `${import.meta.env.BASE_URL}bootstrap/avatarradius`,
//             type: "link",
//             active: false,
//             selected: false,
//             title: "Avatar-Radius",
//           },
//           {
//             path: `${import.meta.env.BASE_URL}bootstrap/avatarsquare`,
//             type: "link",
//             active: false,
//             selected: false,
//             title: "Avatar-Square",
//           },
//           {
//             path: `${import.meta.env.BASE_URL}bootstrap/avatarrounded`,
//             type: "link",
//             active: false,
//             selected: false,
//             title: "Avatar-Rounded",
//           },
//           {
//             path: `${import.meta.env.BASE_URL}bootstrap/badgespills`,
//             type: "link",
//             active: false,
//             selected: false,
//             title: "BadgesPills",
//           },
//           {
//             path: `${import.meta.env.BASE_URL}bootstrap/breadcrumbs`,
//             type: "link",
//             active: false,
//             selected: false,
//             title: "Breadcrumbs",
//           },
//           {
//             path: `${import.meta.env.BASE_URL}bootstrap/buttons`,
//             type: "link",
//             active: false,
//             selected: false,
//             title: "Buttons",
//           },
//           {
//             path: `${import.meta.env.BASE_URL}bootstrap/carousels`,
//             type: "link",
//             active: false,
//             selected: false,
//             title: "Carousels",
//           },
//           {
//             path: `${import.meta.env.BASE_URL}bootstrap/colors`,
//             type: "link",
//             active: false,
//             selected: false,
//             title: "Colors",
//           },
//           {
//             path: `${import.meta.env.BASE_URL}bootstrap/dropdowns`,
//             type: "link",
//             active: false,
//             selected: false,
//             title: "DropDowns",
//           },
//           {
//             path: `${import.meta.env.BASE_URL}bootstrap/listgroups`,
//             type: "link",
//             active: false,
//             selected: false,
//             title: "List-Groups",
//           },
//           {
//             path: `${import.meta.env.BASE_URL}bootstrap/mediaobject`,
//             type: "link",
//             active: false,
//             selected: false,
//             title: "Media-Object",
//           },
//           {
//             path: `${import.meta.env.BASE_URL}bootstrap/modal`,
//             type: "link",
//             active: false,
//             selected: false,
//             title: "Modal",
//           },
//           {
//             path: `${import.meta.env.BASE_URL}bootstrap/navigation`,
//             type: "link",
//             active: false,
//             selected: false,
//             title: "Navigation",
//           },
//           {
//             path: `${import.meta.env.BASE_URL}bootstrap/offcanvas`,
//             type: "link",
//             active: false,
//             selected: false,
//             title: "OffCanvas",
//           },
//           {
//             path: `${import.meta.env.BASE_URL}bootstrap/pagination`,
//             type: "link",
//             active: false,
//             selected: false,
//             title: "Pagination",
//           },
//           {
//             path: `${import.meta.env.BASE_URL}bootstrap/panels`,
//             type: "link",
//             active: false,
//             selected: false,
//             title: "Panels",
//           },
//           {
//             path: `${import.meta.env.BASE_URL}bootstrap/progress`,
//             type: "link",
//             active: false,
//             selected: false,
//             title: "Progress",
//           },
//           {
//             path: `${import.meta.env.BASE_URL}bootstrap/tabs`,
//             type: "link",
//             active: false,
//             selected: false,
//             title: "Tabs",
//           },
//           {
//             path: `${import.meta.env.BASE_URL}bootstrap/tags`,
//             type: "link",
//             title: "Tags",
//           },
//           {
//             path: `${import.meta.env.BASE_URL}bootstrap/thumbnails`,
//             type: "link",
//             title: "Thumbnails",
//           },
//           {
//             path: `${import.meta.env.BASE_URL}bootstrap/toast`,
//             type: "link",
//             title: "Toast",
//           },
//           {
//             path: `${import.meta.env.BASE_URL}bootstrap/tooltippopover`,
//             type: "link",
//             title: "Tooltip Popover",
//           },
//           {
//             path: `${import.meta.env.BASE_URL}bootstrap/typography`,
//             type: "link",
//             title: "Typography",
//           },
//           {
//             path: `${import.meta.env.BASE_URL}bootstrap/ribbons`,
//             type: "link",
//             title: "Ribbons",
//           },
//         ],
//       },

//       {
//         path: `${import.meta.env.BASE_URL}landingPage/landingPage`,
//         badge: "badge bg-green br-5 side-badge blink-text pb-1",
//         badgetxt: "New",
//         icon: "fe fe-zap",
//         type: "link",
//         active: true,
//         selected: false,
//         title: "Landing Page",
//       },
//     ],
//   },
//   {
//     menutitle: "PRE-BUILD-PAGES",
//     Items: [
//       {
//         title: "Pages",
//         icon: "fe fe-layers",
//         type: "sub",
//         Name: "",
//         Names: "",
//         active: false,
//         selected: false,
//         children: [
//           {
//             path: `${import.meta.env.BASE_URL}pages/editprofile`,
//             type: "link",
//             active: false,
//             selected: false,
//             title: "Edit-profile",
//           },
//           {
//             path: `${import.meta.env.BASE_URL}pages/gallery`,
//             type: "link",
//             active: false,
//             selected: false,
//             title: "Gallery",
//           },
//           {
//             path: `${import.meta.env.BASE_URL}pages/mailcompose`,
//             type: "link",
//             active: false,
//             selected: false,
//             title: "Mail-compose",
//           },
//           {
//             path: `${import.meta.env.BASE_URL}pages/mailinbox`,
//             type: "link",
//             active: false,
//             selected: false,
//             title: "Mail-inbox",
//           },
//           {
//             path: `${import.meta.env.BASE_URL}pages/mailread`,
//             type: "link",
//             active: false,
//             selected: false,
//             title: "Mail-read",
//           },
//           {
//             path: `${import.meta.env.BASE_URL}pages/notificationlist`,
//             type: "link",
//             active: false,
//             selected: false,
//             title: "Notification-list",
//           },
//           {
//             path: `${import.meta.env.BASE_URL}pages/profile`,
//             type: "link",
//             active: false,
//             selected: false,
//             title: "Profile",
//           },

//           {
//             title: "Forms",
//             icon: "ti-face-smile",
//             type: "sub",
//             Name: "",
//             Names: "",
//             active: false,
//             selected: false,
//             children: [
//               {
//                 path: `${import.meta.env.BASE_URL}pages/forms/formadvanced`,
//                 type: "link",
//                 active: false,
//                 selected: false,
//                 title: "Form-advanced",
//               },
//               {
//                 path: `${import.meta.env.BASE_URL}pages/forms/formeditor`,
//                 type: "link",
//                 active: false,
//                 selected: false,
//                 title: "Form-editor",
//               },
//               {
//                 path: `${import.meta.env.BASE_URL}pages/forms/formelements`,
//                 type: "link",
//                 active: false,
//                 selected: false,
//                 title: "Form-elements",
//               },
//               {
//                 path: `${import.meta.env.BASE_URL}pages/forms/formlayouts`,
//                 type: "link",
//                 active: false,
//                 selected: false,
//                 title: "Form-layouts",
//               },
//               {
//                 path: `${import.meta.env.BASE_URL}pages/forms/formvalidation`,
//                 type: "link",
//                 active: false,
//                 selected: false,
//                 title: "Form-validation",
//               },
//               {
//                 path: `${import.meta.env.BASE_URL}pages/forms/formwizard`,
//                 type: "link",
//                 active: false,
//                 selected: false,
//                 title: "Form-wizard",
//               },
//               {
//                 path: `${import.meta.env.BASE_URL}pages/forms/forminputspinner`,
//                 type: "link",
//                 active: false,
//                 selected: false,
//                 title: "Form-input-spinner",
//               },
//             ],
//           },
//           {
//             title: "Table",
//             icon: "ti-face-smile",
//             type: "sub",
//             Name: "",
//             Names: "",
//             active: false,
//             selected: false,
//             children: [
//               {
//                 path: `${import.meta.env.BASE_URL}pages/tables/datatables`,
//                 type: "link",
//                 active: false,
//                 selected: false,
//                 title: "Data-Table",
//               },
//               {
//                 path: `${import.meta.env.BASE_URL}pages/tables/defaulttables`,
//                 type: "link",
//                 active: false,
//                 selected: false,
//                 title: "Default-Table",
//               },
//               {
//                 path: `${import.meta.env.BASE_URL}pages/tables/edittables`,
//                 type: "link",
//                 active: false,
//                 selected: false,
//                 title: "Edit-Table",
//               },
//             ],
//           },
//           {
//             title: "Extension",
//             icon: "ti-face-smile",
//             type: "sub",
//             Name: "",
//             Names: "",
//             active: false,
//             selected: false,
//             children: [
//               {
//                 path: `${import.meta.env.BASE_URL}pages/extension/aboutcompany`,
//                 type: "link",
//                 active: false,
//                 selected: false,
//                 title: "About Company",
//               },
//               {
//                 path: `${import.meta.env.BASE_URL}pages/extension/blogdetails`,
//                 type: "link",
//                 active: false,
//                 selected: false,
//                 title: "Blog Details",
//               },
//               {
//                 path: `${import.meta.env.BASE_URL}pages/extension/blogpost`,
//                 type: "link",
//                 active: false,
//                 selected: false,
//                 title: "Blog Post",
//               },
//               {
//                 path: `${import.meta.env.BASE_URL}pages/extension/blogs`,
//                 type: "link",
//                 active: false,
//                 selected: false,
//                 title: "Blog",
//               },
//               {
//                 path: `${import.meta.env.BASE_URL}pages/extension/emptypage`,
//                 type: "link",
//                 active: false,
//                 selected: false,
//                 title: "Empty Page",
//               },
//               {
//                 path: `${import.meta.env.BASE_URL}pages/extension/faqs`,
//                 type: "link",
//                 active: false,
//                 selected: false,
//                 title: "FAQS",
//               },
//               {
//                 path: `${import.meta.env.BASE_URL}pages/extension/invoice`,
//                 type: "link",
//                 active: false,
//                 selected: false,
//                 title: "Invoice",
//               },
//               {
//                 path: `${import.meta.env.BASE_URL}pages/extension/pricing`,
//                 type: "link",
//                 active: false,
//                 selected: false,
//                 title: "Pricing Table",
//               },
//               {
//                 path: `${import.meta.env.BASE_URL}pages/extension/services`,
//                 type: "link",
//                 active: false,
//                 selected: false,
//                 title: "Services",
//               },
//               {
//                 path: `${import.meta.env.BASE_URL}pages/extension/setting`,
//                 type: "link",
//                 active: false,
//                 selected: false,
//                 title: "Settings",
//               },
//               {
//                 path: `${import.meta.env.BASE_URL}pages/extension/term`,
//                 type: "link",
//                 active: false,
//                 selected: false,
//                 title: "Terms",
//               },
//               {
//                 path: `${
//                   import.meta.env.BASE_URL
//                 }pages/extension/underconstruction`,
//                 type: "link",
//                 active: false,
//                 selected: false,
//                 title: "UnderConstruction",
//               },
//             ],
//           },
//           {
//             path: `${import.meta.env.BASE_URL}pages/switcher/SwitcherStyle1`,
//             type: "link",
//             active: false,
//             selected: false,
//             title: "Switcher",
//           },
//         ],
//       },
//       {
//         title: "E-commerce",
//         icon: "fe fe-shopping-bag",
//         type: "sub",
//         Name: "",
//         Names: "",
//         active: false,
//         selected: false,
//         children: [
//           {
//             path: `${import.meta.env.BASE_URL}ecommerce/addproduct`,
//             type: "link",
//             active: false,
//             selected: false,
//             title: "Add Product",
//           },
//           {
//             path: `${import.meta.env.BASE_URL}ecommerce/checkout`,
//             type: "link",
//             active: false,
//             selected: false,
//             title: "Checkout",
//           },
//           {
//             path: `${import.meta.env.BASE_URL}ecommerce/productdetails`,
//             type: "link",
//             active: false,
//             selected: false,
//             title: "Product Details",
//           },
//           {
//             path: `${import.meta.env.BASE_URL}ecommerce/shop`,
//             type: "link",
//             active: false,
//             selected: false,
//             title: "Shop",
//           },
//           {
//             path: `${import.meta.env.BASE_URL}ecommerce/shoppingcart`,
//             type: "link",
//             active: false,
//             selected: false,
//             title: "ShoppingCart",
//           },
//           {
//             path: `${import.meta.env.BASE_URL}ecommerce/wishlist`,
//             type: "link",
//             active: false,
//             selected: false,
//             title: "Wishlist",
//           },
//         ],
//       },
//       {
//         title: "File-Manager",
//         icon: "fe fe-folder",
//         badge: "badge bg-pink side-badge",
//         badgetxt: "4",
//         type: "sub",
//         Name: "",
//         Names: "",
//         active: false,
//         selected: false,
//         children: [
//           {
//             path: `${import.meta.env.BASE_URL}filemanager/fileattachments`,
//             type: "link",
//             active: false,
//             selected: false,
//             title: "File-Attachments",
//           },
//           {
//             path: `${import.meta.env.BASE_URL}filemanager/filedetails`,
//             type: "link",
//             active: false,
//             selected: false,
//             title: "File Details",
//           },
//           {
//             path: `${import.meta.env.BASE_URL}filemanager/filemanager`,
//             type: "link",
//             active: false,
//             selected: false,
//             title: "File Manager",
//           },
//           {
//             path: `${import.meta.env.BASE_URL}filemanager/filemanagerlist`,
//             type: "link",
//             active: false,
//             selected: false,
//             title: "File-ManagerList",
//           },
//         ],
//       },
//     ],
//   },

//   {
//     menutitle: "MISC PAGES",
//     Items: [
//       {
//         title: "Authentication",
//         icon: "fe fe-users",
//         type: "sub",
//         Name: "",
//         Names: "",
//         active: false,
//         selected: false,
//         children: [
//           {
//             path: `${import.meta.env.BASE_URL}authentication/login`,
//             type: "link",
//             active: false,
//             selected: false,
//             title: "Login",
//           },
//           {
//             path: `${import.meta.env.BASE_URL}authentication/register`,
//             type: "link",
//             active: false,
//             selected: false,
//             title: "Register",
//           },
//           {
//             path: `${import.meta.env.BASE_URL}authentication/forgotpassword`,
//             type: "link",
//             active: false,
//             selected: false,
//             title: "Forgot Password",
//           },
//           {
//             path: `${import.meta.env.BASE_URL}authentication/lockscreen`,
//             type: "link",
//             active: false,
//             selected: false,
//             title: "LockScreen",
//           },
//           {
//             title: "ErrorPage",
//             icon: "ti-face-smile",
//             type: "sub",
//             Name: "",
//             Names: "",
//             active: false,
//             selected: false,
//             children: [
//               {
//                 path: `${
//                   import.meta.env.BASE_URL
//                 }authentication/errorpage/error400`,
//                 type: "link",
//                 active: false,
//                 selected: false,
//                 title: "Error400",
//               },
//               {
//                 path: `${
//                   import.meta.env.BASE_URL
//                 }authentication/errorpage/error401`,
//                 type: "link",
//                 active: false,
//                 selected: false,
//                 title: "Error401",
//               },
//               {
//                 path: `${
//                   import.meta.env.BASE_URL
//                 }authentication/errorpage/error403`,
//                 type: "link",
//                 active: false,
//                 selected: false,
//                 title: "Error403",
//               },
//               {
//                 path: `${
//                   import.meta.env.BASE_URL
//                 }authentication/errorpage/error404`,
//                 type: "link",
//                 active: false,
//                 selected: false,
//                 title: "Error404",
//               },
//               {
//                 path: `${
//                   import.meta.env.BASE_URL
//                 }authentication/errorpage/error500`,
//                 type: "link",
//                 active: false,
//                 selected: false,
//                 title: "Error500",
//               },
//               {
//                 path: `${
//                   import.meta.env.BASE_URL
//                 }authentication/errorpage/error503`,
//                 type: "link",
//                 active: false,
//                 selected: false,
//                 title: "Error503",
//               },
//             ],
//           },
//         ],
//       },
//       {
//         title: "Submenus",
//         icon: " fe fe-cpu",
//         type: "sub",
//         active: false,
//         children: [
//           {
//             path: `${import.meta.env.BASE_URL}#`,
//             title: "SubMenu1",
//             type: "link",
//           },

//           {
//             path: `${import.meta.env.BASE_URL}#`,
//             title: "SubMenu2",
//             type: "sub",
//             children: [
//               {
//                 path: `${import.meta.env.BASE_URL}#`,
//                 title: "SubMenu2-1",
//                 type: "link",
//               },
//               {
//                 path: `${import.meta.env.BASE_URL}#`,
//                 title: "SubMenu2-2",
//                 type: "link",
//               },
//             ],
//           },
//         ],
//       },
//     ],
//   },

//   {
//     menutitle: "GENERAL",
//     Items: [
//       {
//         title: "Maps",
//         icon: "fe fe-map-pin",
//         type: "sub",
//         Name: "",
//         Names: "",
//         children: [
//           {
//             path: `${import.meta.env.BASE_URL}maps/leafletmaps`,
//             type: "link",
//             active: false,
//             selected: false,
//             title: "Leaflet-Maps",
//           },
//           {
//             path: `${import.meta.env.BASE_URL}maps/simplemaps`,
//             type: "link",
//             active: false,
//             selected: false,
//             title: "Simple-Maps",
//           },
//         ],
//       },
//       {
//         title: "Charts",
//         icon: "fe fe-bar-chart-2",
//         type: "sub",
//         Name: "",
//         Names: "",
//         badge: "badge bg-secondary side-badge",
//         badgetxt: "6",
//         children: [
//           {
//             path: `${import.meta.env.BASE_URL}charts/chartjs`,
//             type: "link",
//             active: false,
//             selected: false,
//             title: " Chartjs",
//           },
//           {
//             path: `${import.meta.env.BASE_URL}charts/echart`,
//             type: "sub",
//             Name: "",
//             Names: "",
//             title: " Echart",
//             children: [
//               {
//                 path: `${import.meta.env.BASE_URL}charts/echart/lines`,
//                 type: "link",
//                 active: false,
//                 selected: false,
//                 title: " Line Chart",
//               },
//               {
//                 path: `${import.meta.env.BASE_URL}charts/echart/bar`,
//                 type: "link",
//                 active: false,
//                 selected: false,
//                 title: " Bar Chart",
//               },
//               {
//                 path: `${import.meta.env.BASE_URL}charts/echart/candlestick`,
//                 type: "link",
//                 active: false,
//                 selected: false,
//                 title: " Candle Stick Chart",
//               },

//               {
//                 path: `${import.meta.env.BASE_URL}charts/echart/scatter`,
//                 type: "link",
//                 active: false,
//                 selected: false,
//                 title: " Scatter Chart",
//               },
//               {
//                 path: `${import.meta.env.BASE_URL}charts/echart/tree`,
//                 type: "link",
//                 active: false,
//                 selected: false,
//                 title: " Tree Chart",
//               },
//             ],
//           },

//           {
//             path: `${import.meta.env.BASE_URL}charts/apexchart`,
//             type: "sub",
//             Name: "",
//             Names: "",
//             title: " ApexChart",
//             children: [
//               {
//                 path: `${import.meta.env.BASE_URL}charts/apexchart/line`,
//                 type: "link",
//                 active: false,
//                 selected: false,
//                 title: " Line Chart",
//               },
//               {
//                 path: `${import.meta.env.BASE_URL}charts/apexchart/area`,
//                 type: "link",
//                 active: false,
//                 selected: false,
//                 title: " Area Chart",
//               },
//               {
//                 path: `${import.meta.env.BASE_URL}charts/apexchart/column`,
//                 type: "link",
//                 active: false,
//                 selected: false,
//                 title: " Column Chart",
//               },
//               {
//                 path: `${import.meta.env.BASE_URL}charts/apexchart/bar`,
//                 type: "link",
//                 active: false,
//                 selected: false,
//                 title: " Bar Chart",
//               },
//               {
//                 path: `${import.meta.env.BASE_URL}charts/apexchart/mixed`,
//                 type: "link",
//                 active: false,
//                 selected: false,
//                 title: " Mixed Chart",
//               },
//               {
//                 path: `${import.meta.env.BASE_URL}charts/apexchart/timeline`,
//                 type: "link",
//                 active: false,
//                 selected: false,
//                 title: " Timeline Chart",
//               },
//               {
//                 path: `${import.meta.env.BASE_URL}charts/apexchart/candlestick`,
//                 type: "link",
//                 active: false,
//                 selected: false,
//                 title: " CandleStick Chart",
//               },
//               {
//                 path: `${import.meta.env.BASE_URL}charts/apexchart/boxplot`,
//                 type: "link",
//                 active: false,
//                 selected: false,
//                 title: " Boxplot Chart",
//               },
//               {
//                 path: `${import.meta.env.BASE_URL}charts/apexchart/treemap`,
//                 type: "link",
//                 active: false,
//                 selected: false,
//                 title: " Treemap Chart",
//               },
//               {
//                 path: `${import.meta.env.BASE_URL}charts/apexchart/pie`,
//                 type: "link",
//                 active: false,
//                 selected: false,
//                 title: " Pie Chart",
//               },
//               {
//                 path: `${import.meta.env.BASE_URL}charts/apexchart/radialbar`,
//                 type: "link",
//                 active: false,
//                 selected: false,
//                 title: " Radialbar Chart",
//               },
//               {
//                 path: `${import.meta.env.BASE_URL}charts/apexchart/radar`,
//                 type: "link",
//                 active: false,
//                 selected: false,
//                 title: " Radar Chart",
//               },
//               {
//                 path: `${import.meta.env.BASE_URL}charts/apexchart/polararea`,
//                 type: "link",
//                 active: false,
//                 selected: false,
//                 title: " PolarArea Chart",
//               },
//             ],
//           },
//         ],
//       },
//       {
//         title: "Icons",
//         icon: "fe fe-wind",
//         type: "sub",
//         Name: "",
//         Names: "",
//         children: [
//           {
//             path: `${import.meta.env.BASE_URL}icons/bootstrapicons`,
//             type: "link",
//             active: false,
//             selected: false,
//             title: "Bootstrap Icons",
//           },
//           {
//             path: `${import.meta.env.BASE_URL}icons/feathericons`,
//             type: "link",
//             active: false,
//             selected: false,
//             title: " Feather Icons",
//           },
//           {
//             path: `${import.meta.env.BASE_URL}icons/flagicons`,
//             type: "link",
//             active: false,
//             selected: false,
//             title: " Flag Icons",
//           },
//           {
//             path: `${import.meta.env.BASE_URL}icons/fontawesome`,
//             type: "link",
//             active: false,
//             selected: false,
//             title: "Font-Awesome Icons",
//           },
//           {
//             path: `${import.meta.env.BASE_URL}icons/ionicicons`,
//             type: "link",
//             active: false,
//             selected: false,
//             title: " Ionic Icons",
//           },
//           {
//             path: `${import.meta.env.BASE_URL}icons/materialdesignicons`,
//             type: "link",
//             active: false,
//             selected: false,
//             title: " MaterialDesign Icons",
//           },
//           {
//             path: `${import.meta.env.BASE_URL}icons/pe7icons`,
//             type: "link",
//             active: false,
//             selected: false,
//             title: " Pe7 Icons",
//           },
//           {
//             path: `${import.meta.env.BASE_URL}icons/simplelineicons`,
//             type: "link",
//             active: false,
//             selected: false,
//             title: "Simpleline Icons",
//           },
//           {
//             path: `${import.meta.env.BASE_URL}icons/themifyicons`,
//             type: "link",
//             active: false,
//             selected: false,
//             title: " Themify Icons",
//           },
//           {
//             path: `${import.meta.env.BASE_URL}icons/typiconsicons`,
//             type: "link",
//             active: false,
//             selected: false,
//             title: " Typicons Icons",
//           },
//           {
//             path: `${import.meta.env.BASE_URL}icons/weathericons`,
//             type: "link",
//             active: false,
//             selected: false,
//             title: " Weather Icons",
//           },
//         ],
//       },
//     ],
//   },
// ];
export const MENUITEMS = [
  {
    menutitle: "MAIN",
    Items: [
      {
        path: `${import.meta.env.BASE_URL}dashboard`,
        icon: "fe fe-home",
        type: "link",
        active: false,
        selected: false,
        title: "Dashboard",
      },
    ],
  },
  {
    menutitle: "Listing",
    Items: [
      {
        title: "Listing Page",
        icon: "fe fe-slack",
        type: "sub",
        Name: "",
        Names: "",
        active: false,
        selected: false,
        children: [
          {
            path: `${import.meta.env.BASE_URL}listings`,
            type: "link",
            active: false,
            selected: false,
            title: "Listings",
          },
          {
            path: `${import.meta.env.BASE_URL}my-info`,
            type: "link",
            active: false,
            selected: false,
            title: "Info",
          },
          {
            path: `${import.meta.env.BASE_URL}my-marketing-material`,
            type: "link",
            active: false,
            selected: false,
            title: "Marketing Material",
          },
          {
            path: `${import.meta.env.BASE_URL}my-locations`,
            type: "link",
            active: false,
            selected: false,
            title: "Location",
          },
          {
            path: `${import.meta.env.BASE_URL}my-shows`,
            type: "link",
            active: false,
            selected: false,
            title: "Date & Show Time",
          },
          {
            path: `${import.meta.env.BASE_URL}my-products`,
            type: "link",
            active: false,
            selected: false,
            title: "Product & Pricing",
          },
          {
            path: `${import.meta.env.BASE_URL}my-zoning-and-capacity`,
            type: "link",
            active: false,
            selected: false,
            title: "Zoning & Capacity",
          },
          {
            path: `${import.meta.env.BASE_URL}my-product-allocation`,
            type: "link",
            active: false,
            selected: false,
            title: "Product Allocation",
          },
          {
            path: `${import.meta.env.BASE_URL}my-shops`,
            type: "link",
            active: false,
            selected: false,
            title: "Shops",
          },
          {
            path: `${import.meta.env.BASE_URL}my-rules`,
            type: "link",
            active: false,
            selected: false,
            title: "Rules",
          },
          {
            path: `${import.meta.env.BASE_URL}my-policies`,
            type: "link",
            active: false,
            selected: false,
            title: "Policies",
          },
          // {
          //   path: `${import.meta.env.BASE_URL}seating-plan`,
          //   type: "link",
          //   active: false,
          //   selected: false,
          //   title: "Seat Plan",
          // },
        ],
      },
      {
        path: `${import.meta.env.BASE_URL}orders`,
        icon: "fe fe-file",
        type: "link",
        active: false,
        selected: false,
        title: "Order",
      },
      {
        title: "Designer",
        icon: "fe fe-layers",
        type: "sub",
        Name: "",
        Names: "",
        active: false,
        selected: false,
        children: [
          {
            path: `${import.meta.env.BASE_URL}seating-plan`,
            type: "link",
            active: false,
            selected: false,
            title: "Seat Plan",
          },
          {
            path: `${import.meta.env.BASE_URL}tickets`,
            type: "link",
            active: false,
            selected: false,
            title: "Tickets",
          },
        ],
      },
      {
        title: "Marketing",
        icon: "fe fe-dollar-sign",
        type: "sub",
        Name: "",
        Names: "",
        active: false,
        selected: false,
        children: [
          {
            path: `${import.meta.env.BASE_URL}guest-list`,
            type: "link",
            active: false,
            selected: false,
            title: "Guest Lists",
          },
          {
            path: `${import.meta.env.BASE_URL}promotions`,
            type: "link",
            active: false,
            selected: false,
            title: "Promotions",
          },
          {
            path: `${import.meta.env.BASE_URL}`,
            type: "link",
            active: false,
            selected: false,
            title: "Database",
          },
          {
            path: `${import.meta.env.BASE_URL}`,
            type: "link",
            active: false,
            selected: false,
            title: "Digital",
          },
          {
            path: `${import.meta.env.BASE_URL}`,
            type: "link",
            active: false,
            selected: false,
            title: "Social Media",
          },
          {
            path: `${import.meta.env.BASE_URL}`,
            type: "link",
            active: false,
            selected: false,
            title: "In App",
          },
          {
            path: `${import.meta.env.BASE_URL}`,
            type: "link",
            active: false,
            selected: false,
            title: "Service Kiosks",
          },
          {
            path: `${import.meta.env.BASE_URL}`,
            type: "link",
            active: false,
            selected: false,
            title: "Fliering",
          },
        ],
      },
      {
        title: "Access Control",
        icon: "fe fe-sliders",
        type: "sub",
        Name: "",
        Names: "",
        active: false,
        selected: false,
        children: [
          {
            path: `${import.meta.env.BASE_URL}scanning`,
            type: "link",
            active: false,
            selected: false,
            title: "Scanning",
          },
          {
            path: `${import.meta.env.BASE_URL}`,
            type: "link",
            active: false,
            selected: false,
            title: "Accreditation",
          },
        ],
      },
      {
        title: "General",
        icon: "fe fe-tag",
        type: "sub",
        Name: "",
        Names: "",
        active: false,
        selected: false,
        children: [
          {
            path: `${import.meta.env.BASE_URL}`,
            type: "link",
            active: false,
            selected: false,
            title: "Tickets",
          },
        ],
      },
      {
        title: "Advertisement",
        icon: "fe fe-tv",
        type: "sub",
        Name: "",
        Names: "",
        active: false,
        selected: false,
        children: [
          {
            path: `${import.meta.env.BASE_URL}`,
            type: "link",
            active: false,
            selected: false,
            title: "Boosting",
          },
          {
            path: `${import.meta.env.BASE_URL}`,
            type: "link",
            active: false,
            selected: false,
            title: "Banners",
          },
          {
            path: `${import.meta.env.BASE_URL}`,
            type: "link",
            active: false,
            selected: false,
            title: "TV",
          },
          {
            path: `${import.meta.env.BASE_URL}`,
            type: "link",
            active: false,
            selected: false,
            title: "Radio",
          },
          {
            path: `${import.meta.env.BASE_URL}`,
            type: "link",
            active: false,
            selected: false,
            title: "OOH",
          },
          {
            path: `${import.meta.env.BASE_URL}`,
            type: "link",
            active: false,
            selected: false,
            title: "Print",
          },
        ],
      },
      {
        title: "Others",
        icon: "fe fe-help-circle",
        type: "sub",
        Name: "",
        Names: "",
        active: false,
        selected: false,
        children: [
          {
            path: `${import.meta.env.BASE_URL}`,
            type: "link",
            active: false,
            selected: false,
            title: "Finance",
          },
          {
            path: `${import.meta.env.BASE_URL}`,
            type: "link",
            active: false,
            selected: false,
            title: "Report",
          },
          {
            path: `${import.meta.env.BASE_URL}`,
            type: "link",
            active: false,
            selected: false,
            title: "Legal",
          },
          {
            path: `${import.meta.env.BASE_URL}`,
            type: "link",
            active: false,
            selected: false,
            title: "Setting",
          },
          {
            path: `${import.meta.env.BASE_URL}`,
            type: "link",
            active: false,
            selected: false,
            title: "Help",
          },
        ],
      },
      // {
      //   title: "Designer",
      //   icon: "fe fe-layers",
      //   type: "sub",
      //   active: false,
      //   selected: false,
      //   Names: "mega-slide-menu",
      //   Name: "mega-menu",
      // },
      // {
      //   title: "Guest",
      //   icon: "fe fe-layers",
      //   type: "sub",
      //   active: false,
      //   selected: false,
      //   Names: "mega-slide-menu",
      //   Name: "mega-menu",
      //   children: [
      //     {
      //       path: `${import.meta.env.BASE_URL}guest-list`,
      //       type: "link",
      //       active: false,
      //       selected: false,
      //       title: "Guest List",
      //     },
      //     {
      //       path: `${import.meta.env.BASE_URL}promotions`,
      //       type: "link",
      //       active: false,
      //       selected: false,
      //       title: "Promotions",
      //     },
      //   ],
      // },
      // {
      //   title: "Marketing",
      //   icon: "fe fe-layers",
      //   type: "sub",
      //   active: false,
      //   selected: false,
      //   Names: "mega-slide-menu",
      //   Name: "mega-menu",
      //   children: [
      //     {
      //       path: `${import.meta.env.BASE_URL}`,
      //       type: "link",
      //       active: false,
      //       selected: false,
      //       title: "Marketing",
      //     },
      //     {
      //       path: `${import.meta.env.BASE_URL}`,
      //       type: "link",
      //       active: false,
      //       selected: false,
      //       title: "Database",
      //     },
      //     {
      //       path: `${import.meta.env.BASE_URL}`,
      //       type: "link",
      //       active: false,
      //       selected: false,
      //       title: "Social Media",
      //     },
      //     {
      //       path: `${import.meta.env.BASE_URL}`,
      //       type: "link",
      //       active: false,
      //       selected: false,
      //       title: "In App",
      //     },
      //     {
      //       path: `${import.meta.env.BASE_URL}`,
      //       type: "link",
      //       active: false,
      //       selected: false,
      //       title: "Service Kiosks",
      //     },
      //     {
      //       path: `${import.meta.env.BASE_URL}`,
      //       type: "link",
      //       active: false,
      //       selected: false,
      //       title: "Fliering",
      //     },
      //   ],
      // },
      // {
      //   title: "Advertisement",
      //   icon: "fe fe-layers",
      //   type: "sub",
      //   active: false,
      //   selected: false,
      //   Names: "mega-slide-menu",
      //   Name: "mega-menu",
      //   children: [
      //     {
      //       path: `${import.meta.env.BASE_URL}`,
      //       type: "link",
      //       active: false,
      //       selected: false,
      //       title: "Advertisement",
      //     },
      //     {
      //       path: `${import.meta.env.BASE_URL}`,
      //       type: "link",
      //       active: false,
      //       selected: false,
      //       title: "Boosting",
      //     },
      //     {
      //       path: `${import.meta.env.BASE_URL}`,
      //       type: "link",
      //       active: false,
      //       selected: false,
      //       title: "Banners",
      //     },
      //     {
      //       path: `${import.meta.env.BASE_URL}`,
      //       type: "link",
      //       active: false,
      //       selected: false,
      //       title: "TV",
      //     },
      //     {
      //       path: `${import.meta.env.BASE_URL}`,
      //       type: "link",
      //       active: false,
      //       selected: false,
      //       title: "Radio",
      //     },
      //     {
      //       path: `${import.meta.env.BASE_URL}`,
      //       type: "link",
      //       active: false,
      //       selected: false,
      //       title: "OOH",
      //     },
      //     {
      //       path: `${import.meta.env.BASE_URL}`,
      //       type: "link",
      //       active: false,
      //       selected: false,
      //       title: "Print",
      //     },
      //   ],
      // },
    ],
  },
  // {
  //   menutitle: "PRE-BUILD-PAGES",
  //   Items: [
  //     {
  //       title: "Pages",
  //       icon: "fe fe-layers",
  //       type: "sub",
  //       Name: "",
  //       Names: "",
  //       active: false,
  //       selected: false,
  //       children: [
  //         {
  //           path: `${import.meta.env.BASE_URL}pages/editprofile`,
  //           type: "link",
  //           active: false,
  //           selected: false,
  //           title: "Edit-profile",
  //         },
  //         {
  //           path: `${import.meta.env.BASE_URL}pages/gallery`,
  //           type: "link",
  //           active: false,
  //           selected: false,
  //           title: "Gallery",
  //         },
  //         {
  //           path: `${import.meta.env.BASE_URL}pages/mailcompose`,
  //           type: "link",
  //           active: false,
  //           selected: false,
  //           title: "Mail-compose",
  //         },
  //         {
  //           path: `${import.meta.env.BASE_URL}pages/mailinbox`,
  //           type: "link",
  //           active: false,
  //           selected: false,
  //           title: "Mail-inbox",
  //         },
  //         {
  //           path: `${import.meta.env.BASE_URL}pages/mailread`,
  //           type: "link",
  //           active: false,
  //           selected: false,
  //           title: "Mail-read",
  //         },
  //         {
  //           path: `${import.meta.env.BASE_URL}pages/notificationlist`,
  //           type: "link",
  //           active: false,
  //           selected: false,
  //           title: "Notification-list",
  //         },
  //         {
  //           path: `${import.meta.env.BASE_URL}pages/profile`,
  //           type: "link",
  //           active: false,
  //           selected: false,
  //           title: "Profile",
  //         },

  //         {
  //           title: "Forms",
  //           icon: "ti-face-smile",
  //           type: "sub",
  //           Name: "",
  //           Names: "",
  //           active: false,
  //           selected: false,
  //           children: [
  //             {
  //               path: `${import.meta.env.BASE_URL}pages/forms/formadvanced`,
  //               type: "link",
  //               active: false,
  //               selected: false,
  //               title: "Form-advanced",
  //             },
  //             {
  //               path: `${import.meta.env.BASE_URL}pages/forms/formeditor`,
  //               type: "link",
  //               active: false,
  //               selected: false,
  //               title: "Form-editor",
  //             },
  //             {
  //               path: `${import.meta.env.BASE_URL}pages/forms/formelements`,
  //               type: "link",
  //               active: false,
  //               selected: false,
  //               title: "Form-elements",
  //             },
  //             {
  //               path: `${import.meta.env.BASE_URL}pages/forms/formlayouts`,
  //               type: "link",
  //               active: false,
  //               selected: false,
  //               title: "Form-layouts",
  //             },
  //             {
  //               path: `${import.meta.env.BASE_URL}pages/forms/formvalidation`,
  //               type: "link",
  //               active: false,
  //               selected: false,
  //               title: "Form-validation",
  //             },
  //             {
  //               path: `${import.meta.env.BASE_URL}pages/forms/formwizard`,
  //               type: "link",
  //               active: false,
  //               selected: false,
  //               title: "Form-wizard",
  //             },
  //             {
  //               path: `${import.meta.env.BASE_URL}pages/forms/forminputspinner`,
  //               type: "link",
  //               active: false,
  //               selected: false,
  //               title: "Form-input-spinner",
  //             },
  //           ],
  //         },
  //         {
  //           title: "Table",
  //           icon: "ti-face-smile",
  //           type: "sub",
  //           Name: "",
  //           Names: "",
  //           active: false,
  //           selected: false,
  //           children: [
  //             {
  //               path: `${import.meta.env.BASE_URL}pages/tables/datatables`,
  //               type: "link",
  //               active: false,
  //               selected: false,
  //               title: "Data-Table",
  //             },
  //             {
  //               path: `${import.meta.env.BASE_URL}pages/tables/defaulttables`,
  //               type: "link",
  //               active: false,
  //               selected: false,
  //               title: "Default-Table",
  //             },
  //             {
  //               path: `${import.meta.env.BASE_URL}pages/tables/edittables`,
  //               type: "link",
  //               active: false,
  //               selected: false,
  //               title: "Edit-Table",
  //             },
  //           ],
  //         },
  //         {
  //           title: "Extension",
  //           icon: "ti-face-smile",
  //           type: "sub",
  //           Name: "",
  //           Names: "",
  //           active: false,
  //           selected: false,
  //           children: [
  //             {
  //               path: `${import.meta.env.BASE_URL}pages/extension/aboutcompany`,
  //               type: "link",
  //               active: false,
  //               selected: false,
  //               title: "About Company",
  //             },
  //             {
  //               path: `${import.meta.env.BASE_URL}pages/extension/blogdetails`,
  //               type: "link",
  //               active: false,
  //               selected: false,
  //               title: "Blog Details",
  //             },
  //             {
  //               path: `${import.meta.env.BASE_URL}pages/extension/blogpost`,
  //               type: "link",
  //               active: false,
  //               selected: false,
  //               title: "Blog Post",
  //             },
  //             {
  //               path: `${import.meta.env.BASE_URL}pages/extension/blogs`,
  //               type: "link",
  //               active: false,
  //               selected: false,
  //               title: "Blog",
  //             },
  //             {
  //               path: `${import.meta.env.BASE_URL}pages/extension/emptypage`,
  //               type: "link",
  //               active: false,
  //               selected: false,
  //               title: "Empty Page",
  //             },
  //             {
  //               path: `${import.meta.env.BASE_URL}pages/extension/faqs`,
  //               type: "link",
  //               active: false,
  //               selected: false,
  //               title: "FAQS",
  //             },
  //             {
  //               path: `${import.meta.env.BASE_URL}pages/extension/invoice`,
  //               type: "link",
  //               active: false,
  //               selected: false,
  //               title: "Invoice",
  //             },
  //             {
  //               path: `${import.meta.env.BASE_URL}pages/extension/pricing`,
  //               type: "link",
  //               active: false,
  //               selected: false,
  //               title: "Pricing Table",
  //             },
  //             {
  //               path: `${import.meta.env.BASE_URL}pages/extension/services`,
  //               type: "link",
  //               active: false,
  //               selected: false,
  //               title: "Services",
  //             },
  //             {
  //               path: `${import.meta.env.BASE_URL}pages/extension/setting`,
  //               type: "link",
  //               active: false,
  //               selected: false,
  //               title: "Settings",
  //             },
  //             {
  //               path: `${import.meta.env.BASE_URL}pages/extension/term`,
  //               type: "link",
  //               active: false,
  //               selected: false,
  //               title: "Terms",
  //             },
  //             {
  //               path: `${
  //                 import.meta.env.BASE_URL
  //               }pages/extension/underconstruction`,
  //               type: "link",
  //               active: false,
  //               selected: false,
  //               title: "UnderConstruction",
  //             },
  //           ],
  //         },
  //         {
  //           path: `${import.meta.env.BASE_URL}pages/switcher/SwitcherStyle1`,
  //           type: "link",
  //           active: false,
  //           selected: false,
  //           title: "Switcher",
  //         },
  //       ],
  //     },
  //     {
  //       title: "E-commerce",
  //       icon: "fe fe-shopping-bag",
  //       type: "sub",
  //       Name: "",
  //       Names: "",
  //       active: false,
  //       selected: false,
  //       children: [
  //         {
  //           path: `${import.meta.env.BASE_URL}ecommerce/addproduct`,
  //           type: "link",
  //           active: false,
  //           selected: false,
  //           title: "Add Product",
  //         },
  //         {
  //           path: `${import.meta.env.BASE_URL}ecommerce/checkout`,
  //           type: "link",
  //           active: false,
  //           selected: false,
  //           title: "Checkout",
  //         },
  //         {
  //           path: `${import.meta.env.BASE_URL}ecommerce/productdetails`,
  //           type: "link",
  //           active: false,
  //           selected: false,
  //           title: "Product Details",
  //         },
  //         {
  //           path: `${import.meta.env.BASE_URL}ecommerce/shop`,
  //           type: "link",
  //           active: false,
  //           selected: false,
  //           title: "Shop",
  //         },
  //         {
  //           path: `${import.meta.env.BASE_URL}ecommerce/shoppingcart`,
  //           type: "link",
  //           active: false,
  //           selected: false,
  //           title: "ShoppingCart",
  //         },
  //         {
  //           path: `${import.meta.env.BASE_URL}ecommerce/wishlist`,
  //           type: "link",
  //           active: false,
  //           selected: false,
  //           title: "Wishlist",
  //         },
  //       ],
  //     },
  //     {
  //       title: "File-Manager",
  //       icon: "fe fe-folder",
  //       badge: "badge bg-pink side-badge",
  //       badgetxt: "4",
  //       type: "sub",
  //       Name: "",
  //       Names: "",
  //       active: false,
  //       selected: false,
  //       children: [
  //         {
  //           path: `${import.meta.env.BASE_URL}filemanager/fileattachments`,
  //           type: "link",
  //           active: false,
  //           selected: false,
  //           title: "File-Attachments",
  //         },
  //         {
  //           path: `${import.meta.env.BASE_URL}filemanager/filedetails`,
  //           type: "link",
  //           active: false,
  //           selected: false,
  //           title: "File Details",
  //         },
  //         {
  //           path: `${import.meta.env.BASE_URL}filemanager/filemanager`,
  //           type: "link",
  //           active: false,
  //           selected: false,
  //           title: "File Manager",
  //         },
  //         {
  //           path: `${import.meta.env.BASE_URL}filemanager/filemanagerlist`,
  //           type: "link",
  //           active: false,
  //           selected: false,
  //           title: "File-ManagerList",
  //         },
  //       ],
  //     },
  //   ],
  // },

  // {
  //   menutitle: "MISC PAGES",
  //   Items: [
  //     {
  //       title: "Authentication",
  //       icon: "fe fe-users",
  //       type: "sub",
  //       Name: "",
  //       Names: "",
  //       active: false,
  //       selected: false,
  //       children: [
  //         {
  //           path: `${import.meta.env.BASE_URL}authentication/login`,
  //           type: "link",
  //           active: false,
  //           selected: false,
  //           title: "Login",
  //         },
  //         {
  //           path: `${import.meta.env.BASE_URL}authentication/register`,
  //           type: "link",
  //           active: false,
  //           selected: false,
  //           title: "Register",
  //         },
  //         {
  //           path: `${import.meta.env.BASE_URL}authentication/forgotpassword`,
  //           type: "link",
  //           active: false,
  //           selected: false,
  //           title: "Forgot Password",
  //         },
  //         {
  //           path: `${import.meta.env.BASE_URL}authentication/lockscreen`,
  //           type: "link",
  //           active: false,
  //           selected: false,
  //           title: "LockScreen",
  //         },
  //         {
  //           title: "ErrorPage",
  //           icon: "ti-face-smile",
  //           type: "sub",
  //           Name: "",
  //           Names: "",
  //           active: false,
  //           selected: false,
  //           children: [
  //             {
  //               path: `${
  //                 import.meta.env.BASE_URL
  //               }authentication/errorpage/error400`,
  //               type: "link",
  //               active: false,
  //               selected: false,
  //               title: "Error400",
  //             },
  //             {
  //               path: `${
  //                 import.meta.env.BASE_URL
  //               }authentication/errorpage/error401`,
  //               type: "link",
  //               active: false,
  //               selected: false,
  //               title: "Error401",
  //             },
  //             {
  //               path: `${
  //                 import.meta.env.BASE_URL
  //               }authentication/errorpage/error403`,
  //               type: "link",
  //               active: false,
  //               selected: false,
  //               title: "Error403",
  //             },
  //             {
  //               path: `${
  //                 import.meta.env.BASE_URL
  //               }authentication/errorpage/error404`,
  //               type: "link",
  //               active: false,
  //               selected: false,
  //               title: "Error404",
  //             },
  //             {
  //               path: `${
  //                 import.meta.env.BASE_URL
  //               }authentication/errorpage/error500`,
  //               type: "link",
  //               active: false,
  //               selected: false,
  //               title: "Error500",
  //             },
  //             {
  //               path: `${
  //                 import.meta.env.BASE_URL
  //               }authentication/errorpage/error503`,
  //               type: "link",
  //               active: false,
  //               selected: false,
  //               title: "Error503",
  //             },
  //           ],
  //         },
  //       ],
  //     },
  //     {
  //       title: "Submenus",
  //       icon: " fe fe-cpu",
  //       type: "sub",
  //       active: false,
  //       children: [
  //         {
  //           path: `${import.meta.env.BASE_URL}#`,
  //           title: "SubMenu1",
  //           type: "link",
  //         },

  //         {
  //           path: `${import.meta.env.BASE_URL}#`,
  //           title: "SubMenu2",
  //           type: "sub",
  //           children: [
  //             {
  //               path: `${import.meta.env.BASE_URL}#`,
  //               title: "SubMenu2-1",
  //               type: "link",
  //             },
  //             {
  //               path: `${import.meta.env.BASE_URL}#`,
  //               title: "SubMenu2-2",
  //               type: "link",
  //             },
  //           ],
  //         },
  //       ],
  //     },
  //   ],
  // },

  // {
  //   menutitle: "GENERAL",
  //   Items: [
  //     {
  //       title: "Maps",
  //       icon: "fe fe-map-pin",
  //       type: "sub",
  //       Name: "",
  //       Names: "",
  //       children: [
  //         {
  //           path: `${import.meta.env.BASE_URL}maps/leafletmaps`,
  //           type: "link",
  //           active: false,
  //           selected: false,
  //           title: "Leaflet-Maps",
  //         },
  //         {
  //           path: `${import.meta.env.BASE_URL}maps/simplemaps`,
  //           type: "link",
  //           active: false,
  //           selected: false,
  //           title: "Simple-Maps",
  //         },
  //       ],
  //     },
  //     {
  //       title: "Charts",
  //       icon: "fe fe-bar-chart-2",
  //       type: "sub",
  //       Name: "",
  //       Names: "",
  //       badge: "badge bg-secondary side-badge",
  //       badgetxt: "6",
  //       children: [
  //         {
  //           path: `${import.meta.env.BASE_URL}charts/chartjs`,
  //           type: "link",
  //           active: false,
  //           selected: false,
  //           title: " Chartjs",
  //         },
  //         {
  //           path: `${import.meta.env.BASE_URL}charts/echart`,
  //           type: "sub",
  //           Name: "",
  //           Names: "",
  //           title: " Echart",
  //           children: [
  //             {
  //               path: `${import.meta.env.BASE_URL}charts/echart/lines`,
  //               type: "link",
  //               active: false,
  //               selected: false,
  //               title: " Line Chart",
  //             },
  //             {
  //               path: `${import.meta.env.BASE_URL}charts/echart/bar`,
  //               type: "link",
  //               active: false,
  //               selected: false,
  //               title: " Bar Chart",
  //             },
  //             {
  //               path: `${import.meta.env.BASE_URL}charts/echart/candlestick`,
  //               type: "link",
  //               active: false,
  //               selected: false,
  //               title: " Candle Stick Chart",
  //             },

  //             {
  //               path: `${import.meta.env.BASE_URL}charts/echart/scatter`,
  //               type: "link",
  //               active: false,
  //               selected: false,
  //               title: " Scatter Chart",
  //             },
  //             {
  //               path: `${import.meta.env.BASE_URL}charts/echart/tree`,
  //               type: "link",
  //               active: false,
  //               selected: false,
  //               title: " Tree Chart",
  //             },
  //           ],
  //         },

  //         {
  //           path: `${import.meta.env.BASE_URL}charts/apexchart`,
  //           type: "sub",
  //           Name: "",
  //           Names: "",
  //           title: " ApexChart",
  //           children: [
  //             {
  //               path: `${import.meta.env.BASE_URL}charts/apexchart/line`,
  //               type: "link",
  //               active: false,
  //               selected: false,
  //               title: " Line Chart",
  //             },
  //             {
  //               path: `${import.meta.env.BASE_URL}charts/apexchart/area`,
  //               type: "link",
  //               active: false,
  //               selected: false,
  //               title: " Area Chart",
  //             },
  //             {
  //               path: `${import.meta.env.BASE_URL}charts/apexchart/column`,
  //               type: "link",
  //               active: false,
  //               selected: false,
  //               title: " Column Chart",
  //             },
  //             {
  //               path: `${import.meta.env.BASE_URL}charts/apexchart/bar`,
  //               type: "link",
  //               active: false,
  //               selected: false,
  //               title: " Bar Chart",
  //             },
  //             {
  //               path: `${import.meta.env.BASE_URL}charts/apexchart/mixed`,
  //               type: "link",
  //               active: false,
  //               selected: false,
  //               title: " Mixed Chart",
  //             },
  //             {
  //               path: `${import.meta.env.BASE_URL}charts/apexchart/timeline`,
  //               type: "link",
  //               active: false,
  //               selected: false,
  //               title: " Timeline Chart",
  //             },
  //             {
  //               path: `${import.meta.env.BASE_URL}charts/apexchart/candlestick`,
  //               type: "link",
  //               active: false,
  //               selected: false,
  //               title: " CandleStick Chart",
  //             },
  //             {
  //               path: `${import.meta.env.BASE_URL}charts/apexchart/boxplot`,
  //               type: "link",
  //               active: false,
  //               selected: false,
  //               title: " Boxplot Chart",
  //             },
  //             {
  //               path: `${import.meta.env.BASE_URL}charts/apexchart/treemap`,
  //               type: "link",
  //               active: false,
  //               selected: false,
  //               title: " Treemap Chart",
  //             },
  //             {
  //               path: `${import.meta.env.BASE_URL}charts/apexchart/pie`,
  //               type: "link",
  //               active: false,
  //               selected: false,
  //               title: " Pie Chart",
  //             },
  //             {
  //               path: `${import.meta.env.BASE_URL}charts/apexchart/radialbar`,
  //               type: "link",
  //               active: false,
  //               selected: false,
  //               title: " Radialbar Chart",
  //             },
  //             {
  //               path: `${import.meta.env.BASE_URL}charts/apexchart/radar`,
  //               type: "link",
  //               active: false,
  //               selected: false,
  //               title: " Radar Chart",
  //             },
  //             {
  //               path: `${import.meta.env.BASE_URL}charts/apexchart/polararea`,
  //               type: "link",
  //               active: false,
  //               selected: false,
  //               title: " PolarArea Chart",
  //             },
  //           ],
  //         },
  //       ],
  //     },
  //     {
  //       title: "Icons",
  //       icon: "fe fe-wind",
  //       type: "sub",
  //       Name: "",
  //       Names: "",
  //       children: [
  //         {
  //           path: `${import.meta.env.BASE_URL}icons/bootstrapicons`,
  //           type: "link",
  //           active: false,
  //           selected: false,
  //           title: "Bootstrap Icons",
  //         },
  //         {
  //           path: `${import.meta.env.BASE_URL}icons/feathericons`,
  //           type: "link",
  //           active: false,
  //           selected: false,
  //           title: " Feather Icons",
  //         },
  //         {
  //           path: `${import.meta.env.BASE_URL}icons/flagicons`,
  //           type: "link",
  //           active: false,
  //           selected: false,
  //           title: " Flag Icons",
  //         },
  //         {
  //           path: `${import.meta.env.BASE_URL}icons/fontawesome`,
  //           type: "link",
  //           active: false,
  //           selected: false,
  //           title: "Font-Awesome Icons",
  //         },
  //         {
  //           path: `${import.meta.env.BASE_URL}icons/ionicicons`,
  //           type: "link",
  //           active: false,
  //           selected: false,
  //           title: " Ionic Icons",
  //         },
  //         {
  //           path: `${import.meta.env.BASE_URL}icons/materialdesignicons`,
  //           type: "link",
  //           active: false,
  //           selected: false,
  //           title: " MaterialDesign Icons",
  //         },
  //         {
  //           path: `${import.meta.env.BASE_URL}icons/pe7icons`,
  //           type: "link",
  //           active: false,
  //           selected: false,
  //           title: " Pe7 Icons",
  //         },
  //         {
  //           path: `${import.meta.env.BASE_URL}icons/simplelineicons`,
  //           type: "link",
  //           active: false,
  //           selected: false,
  //           title: "Simpleline Icons",
  //         },
  //         {
  //           path: `${import.meta.env.BASE_URL}icons/themifyicons`,
  //           type: "link",
  //           active: false,
  //           selected: false,
  //           title: " Themify Icons",
  //         },
  //         {
  //           path: `${import.meta.env.BASE_URL}icons/typiconsicons`,
  //           type: "link",
  //           active: false,
  //           selected: false,
  //           title: " Typicons Icons",
  //         },
  //         {
  //           path: `${import.meta.env.BASE_URL}icons/weathericons`,
  //           type: "link",
  //           active: false,
  //           selected: false,
  //           title: " Weather Icons",
  //         },
  //       ],
  //     },
  //   ],
  // },
];
const dashboardUrl = ["/dashboard"];
const listingsUrl = [
  "/listings",
  "/add-listing/info",
  "/add-listing/location",
  "/add-listing/date-show-time",
  "/add-listing/add-policies",
  "/add-listing/rules",
  "/add-listing/products",
  "/add-listing/zoning-and-capacity",
  "/add-listing/dynamic-pricing",
  "/add-listing/marketing-material",
];
const shopsUrl = ["/my-shops", "/add-shop", "/edit-shop/:id"];
const seatingPlanUrl = ["/seating-plan"];
const guestListUrl = [
  "/guest-list",
  "/single-invitation",
  "/single-invitation",
];
const promotionsUrl = [
  "/promotions",
  "/generate-barcode",
  "/generate-discountcode",
  "/promotions-import",
];

export const SIDE_MENU_ITEM_ONE = [
  {
    title: "Dashboard",
    icon: "fe fe-home",
    href: "/dashboard",
    urls: dashboardUrl,
    fontWeight: "fw-600",
  },
  {
    title: "Listings",
    icon: "fe fe-list",
    href: "/listings",
    urls: listingsUrl,
    fontWeight: "fw-600",
  },
  {
    title: "Info",
    icon: "fe fe-shopping-bag",
    href: "/my-info",
    urls: ["/my-info", "/add-info"],
  },
  {
    title: "Location",
    icon: "fe fe-shopping-bag",
    href: "/my-locations",
    urls: ["/my-locations", "/add-location"],
  },
  {
    title: "Date & Show Time",
    icon: "fe fe-shopping-bag",
    href: "/my-shows",
    urls: ["/my-shows", "/add-show"],
  },
  {
    title: "Products",
    icon: "fe fe-shopping-bag",
    href: "/my-products",
    urls: ["/my-products", "/add-product"],
  },
  {
    title: "Zoning & Capacity",
    icon: "fe fe-shopping-bag",
    href: "/my-zoning-and-capacity",
    urls: ["/my-zoning-and-capacity", "/add-zoning-and-capacity"],
  },
  {
    title: "Shops",
    icon: "fe fe-shopping-bag",
    href: "/my-shops",
    urls: shopsUrl,
  },
  // {
  //   title: "Dynamic Pricing",
  //   icon: "fe fe-zap",
  //   href: "/my-dynamic-pricing",
  //   urls: ["/my-dynamic-pricing", "/add-dynamic-pricing"],
  // },
  {
    title: "Marketing Material",
    icon: "fe fe-zap",
    href: "/my-marketing-material",
    urls: ["/my-marketing-material", "/add-marketing-material"],
  },
  {
    title: "Rules",
    icon: "fe fe-zap",
    href: "/my-rules",
    urls: ["/my-rules", "/add-rule"],
  },
  {
    title: "Policies",
    icon: "fe fe-zap",
    href: "my-policies",
    urls: ["/my-policies", "/add-policy"],
  },
];
export const SIDE_MENU_ITEM_DESIGNER = [
  {
    title: "Designer",
    icon: "fe fe-layers",
    href: "/seating-plan",
    urls: [],
    fontWeight: "fw-600",
  },
  {
    title: "Seat Plan",
    icon: "fe fe-layers",
    href: "/seating-plan",
    urls: seatingPlanUrl,
  },
  {
    title: "Tickets",
    icon: "fe fe-cpu",
  },
];
export const SIDE_MENU_ITEM_MARKETING = [
  {
    title: "Marketing",
    icon: "fe fe-layers",
    href: "/",
    fontWeight: "fw-600",
    underDevelopment: true,
  },
  {
    title: "Database",
    icon: "fe fe-layers",
    href: "/",
    underDevelopment: true,
  },
  {
    title: "Digital",
    icon: "fe fe-cpu",
    underDevelopment: true,
    href: "/",
  },
  {
    title: "Social Media",
    icon: "fe fe-cpu",
    underDevelopment: true,
    href: "/",
  },
  {
    title: "In App",
    icon: "fe fe-cpu",
    underDevelopment: true,
    href: "/",
  },
  {
    title: "Service Kiosks",
    icon: "fe fe-cpu",
    underDevelopment: true,
    href: "/",
  },
  {
    title: "Fliering",
    icon: "fe fe-cpu",
    underDevelopment: true,
    href: "/",
  },
];
export const SIDE_MENU_ITEM_ADVERTISEMENT = [
  {
    title: "Advertisement",
    icon: "fe fe-layers",
    href: "/",
    fontWeight: "fw-600",
    underDevelopment: true,
  },
  {
    title: "Boosting",
    icon: "fe fe-layers",
    href: "/",
    underDevelopment: true,
  },
  {
    title: "Banners",
    icon: "fe fe-cpu",
    underDevelopment: true,
    href: "/",
  },
  {
    title: "TV",
    icon: "fe fe-cpu",
    underDevelopment: true,
    href: "/",
  },
  {
    title: "Radio",
    icon: "fe fe-cpu",
    underDevelopment: true,
    href: "/",
  },
  {
    title: "OOH",
    icon: "fe fe-cpu",
    underDevelopment: true,
    href: "/",
  },
  {
    title: "Print",
    icon: "fe fe-cpu",
    underDevelopment: true,
    href: "/",
  },
];
export const SIDE_MENU_ITEM_GUEST = [
  {
    title: "Guest List",
    icon: "fe fe-users",
    href: "/guest-list",
    urls: guestListUrl,
    fontWeight: "fw-600",
  },
  {
    title: "Promotions",
    icon: "fe fe-command",
    href: "/promotions",
    urls: promotionsUrl,
  },
];
export const SIDE_MENU_ITEM_TWO = [
  {
    title: "Scanning",
    icon: "fe fe-compass",
    fontWeight: "fw-600",
  },
  {
    title: "Accredition",
    icon: "fe fe-wind",
    fontWeight: "fw-600",
  },
];
export const SIDE_MENU_ITEM_THREE = [
  {
    title: "Finance",
    icon: "fe fe-dollar-sign",
    fontWeight: "fw-600",
  },
  {
    title: "Reports",
    icon: "fe fe-flag",
    fontWeight: "fw-600",
  },
  {
    title: "Legal",
    icon: "fe fe-sliders",
    fontWeight: "fw-600",
  },
  {
    title: "Setting",
    icon: "fe fe-settings",
    fontWeight: "fw-600",
  },
  {
    title: "Help",
    icon: "fe fe-settings",
    fontWeight: "fw-600",
  },
];
export const SIDE_ITEM_NEED_HELP = [
  {
    title: "Need Help?",
    icon: "typcn typcn-info-large",
  },
];
