import Owl from "../../assets/images/owl.jpg";
import Business from "../../assets/images/business-meeting.jpg";
import Entertainment from "../../assets/images/entertainment.jpg";
import { IPricingDetailsProps } from "../../components/pricing/AddPricing/type";

export const allPricingDetailsData: IPricingDetailsProps[] = [
  {
    id: 1,
    productDetails: {
      productName: "VIP Concert Ticket",
      productType: "Concert",
      productCategory: "Entertainment",
      productSubCategory: "Music",
      productSubTitle: "Exclusive access to the front row of the concert",
      img: Entertainment,
    },
    rulesAndTimeline: {
      minOrder: "1",
      maxOrder: "4",
      access: "VIP Lounge, Front Row",
      scan: "QR Code",
      salesStartDate: "2024-09-15",
      salesEndDate: "2024-10-10",
    },
    inclusion: {
      inclusionList: ["1", "22", "1111"],
    },
    pricing: {
      netSalesPrice: 100,
      transactionCurrency: "AED",
      vatTax: undefined,
      entertainmentTax: undefined,
      municipalTax: undefined,
      otherTax: undefined,
    },
  },
  {
    id: 2,
    productDetails: {
      productName: "Regular Festival Ticket",
      productType: "Festival",
      productCategory: "Cultural",
      productSubCategory: "Traditional",
      productSubTitle: "Access to all festival activities",
      img: Owl,
    },
    rulesAndTimeline: {
      minOrder: "1",
      maxOrder: "10",
      access: "General Admission",
      scan: "Barcode",
      salesStartDate: "2024-10-01",
      salesEndDate: "2024-12-01",
    },
    inclusion: {
      inclusionList: ["1", "1111"],
    },
    pricing: {
      netSalesPrice: 100,
      transactionCurrency: "AED",
      vatTax: undefined,
      entertainmentTax: undefined,
      municipalTax: undefined,
      otherTax: undefined,
    },
  },
  {
    id: 3,
    productDetails: {
      productName: "Business Pass",
      productType: "Pass",
      productCategory: "Business",
      productSubCategory: "Networking",
      productSubTitle: "Includes conference materials and lunch",
      img: Business,
    },
    rulesAndTimeline: {
      minOrder: "1",
      maxOrder: "5",
      access: "Conference Hall, Networking Area",
      scan: "QR Code",
      salesStartDate: "2024-11-01",
      salesEndDate: "2024-12-15",
    },
    inclusion: {
      inclusionList: [],
    },
    pricing: {
      netSalesPrice: 100,
      transactionCurrency: "AED",
      vatTax: undefined,
      entertainmentTax: undefined,
      municipalTax: undefined,
      otherTax: undefined,
    },
  },
  {
    id: 3,
    productDetails: {
      productName: "Regular Festival Ticket",
      productType: "Festival",
      productCategory: "Cultural",
      productSubCategory: "Traditional",
      productSubTitle: "Access to all festival activities",
      img: Owl,
    },
    rulesAndTimeline: {
      minOrder: "1",
      maxOrder: "10",
      access: "General Admission",
      scan: "Barcode",
      salesStartDate: "2024-10-01",
      salesEndDate: "2024-12-01",
    },
    inclusion: {
      inclusionList: ["1", "22", "1111"],
    },
    pricing: {
      netSalesPrice: 100,
      transactionCurrency: "AED",
      vatTax: undefined,
      entertainmentTax: undefined,
      municipalTax: undefined,
      otherTax: undefined,
    },
  },
  {
    productDetails: {
      productName: "VIP Concert Ticket",
      productType: "Concert",
      productCategory: "Entertainment",
      productSubCategory: "Music",
      productSubTitle: "Exclusive access to the front row of the concert",
      img: Entertainment,
    },
    rulesAndTimeline: {
      minOrder: "1",
      maxOrder: "4",
      access: "VIP Lounge, Front Row",
      scan: "QR Code",
      salesStartDate: "2024-09-15",
      salesEndDate: "2024-10-10",
    },
    inclusion: {
      inclusionList: [],
    },
    pricing: {
      netSalesPrice: 100,
      transactionCurrency: "AED",
      vatTax: undefined,
      entertainmentTax: undefined,
      municipalTax: undefined,
      otherTax: undefined,
    },
    id: 0,
  },
  {
    productDetails: {
      productName: "Regular Festival Ticket",
      productType: "Festival",
      productCategory: "Cultural",
      productSubCategory: "Traditional",
      productSubTitle: "Access to all festival activities",
      img: Owl,
    },
    rulesAndTimeline: {
      minOrder: "1",
      maxOrder: "10",
      access: "General Admission",
      scan: "Barcode",
      salesStartDate: "2024-10-01",
      salesEndDate: "2024-12-01",
    },
    inclusion: {
      inclusionList: ["1", "22", "1111"],
    },
    pricing: {
      netSalesPrice: 100,
      transactionCurrency: "AED",
      vatTax: undefined,
      entertainmentTax: undefined,
      municipalTax: undefined,
      otherTax: undefined,
    },
    id: 0,
  },
  {
    productDetails: {
      productName: "Regular Festival Ticket",
      productType: "Festival",
      productCategory: "Cultural",
      productSubCategory: "Traditional",
      productSubTitle: "Access to all festival activities",
      img: Owl,
    },
    rulesAndTimeline: {
      minOrder: "1",
      maxOrder: "10",
      access: "General Admission",
      scan: "Barcode",
      salesStartDate: "2024-10-01",
      salesEndDate: "2024-12-01",
    },
    inclusion: {
      inclusionList: ["1", "22", "1111", "1", "22", "1111"],
    },
    pricing: {
      netSalesPrice: 100,
      transactionCurrency: "AED",
      vatTax: undefined,
      entertainmentTax: undefined,
      municipalTax: undefined,
      otherTax: undefined,
    },
    id: 0,
  },
  {
    productDetails: {
      productName: "Regular Festival Ticket",
      productType: "Festival",
      productCategory: "Cultural",
      productSubCategory: "Traditional",
      productSubTitle: "Access to all festival activities",
      img: Owl,
    },
    rulesAndTimeline: {
      minOrder: "1",
      maxOrder: "10",
      access: "General Admission",
      scan: "Barcode",
      salesStartDate: "2024-10-01",
      salesEndDate: "2024-12-01",
    },
    inclusion: {
      inclusionList: ["1", "22", "1111", "1", "22", "1111"],
    },
    pricing: {
      netSalesPrice: 100,
      transactionCurrency: "AED",
      vatTax: undefined,
      entertainmentTax: undefined,
      municipalTax: undefined,
      otherTax: undefined,
    },
    id: 0,
  },
  {
    productDetails: {
      productName: "Business Pass",
      productType: "Pass",
      productCategory: "Business",
      productSubCategory: "Networking",
      productSubTitle: "Includes conference materials and lunch",
      img: Business,
    },
    rulesAndTimeline: {
      minOrder: "1",
      maxOrder: "5",
      access: "Conference Hall, Networking Area",
      scan: "QR Code",
      salesStartDate: "2024-11-01",
      salesEndDate: "2024-12-15",
    },
    inclusion: {
      inclusionList: [],
    },
    pricing: {
      netSalesPrice: 100,
      transactionCurrency: "AED",
      vatTax: undefined,
      entertainmentTax: undefined,
      municipalTax: undefined,
      otherTax: undefined,
    },
    id: 0,
  },
  {
    productDetails: {
      productName: "Business Pass",
      productType: "Conference",
      productCategory: "Business",
      productSubCategory: "Networking",
      productSubTitle: "Includes conference materials and lunch",
      img: Business,
    },
    rulesAndTimeline: {
      minOrder: "1",
      maxOrder: "5",
      access: "Conference Hall, Networking Area",
      scan: "QR Code",
      salesStartDate: "2024-11-01",
      salesEndDate: "2024-12-15",
    },
    inclusion: {
      inclusionList: ["1", "22", "1111", "1", "22", "1111"],
    },
    pricing: {
      netSalesPrice: 100,
      transactionCurrency: "AED",
      vatTax: undefined,
      entertainmentTax: undefined,
      municipalTax: undefined,
      otherTax: undefined,
    },
    id: 0,
  },
];

export const entertainmentPricingDetailsData: IPricingDetailsProps[] = [
  {
    productDetails: {
      productName: "Exclusive Concert Experience",
      productType: "Concert",
      productCategory: "Entertainment",
      productSubCategory: "Music",
      productSubTitle: "Access to VIP seating with backstage tour",
      img: Entertainment,
    },
    rulesAndTimeline: {
      minOrder: "1",
      maxOrder: "2",
      access: "VIP Seating, Backstage Tour",
      scan: "QR Code",
      salesStartDate: "2024-09-10",
      salesEndDate: "2024-10-01",
    },
    inclusion: {
      inclusionList: ["1", "22", "1111"],
    },
    pricing: {
      netSalesPrice: 100,
      transactionCurrency: "AED",
      vatTax: undefined,
      entertainmentTax: undefined,
      municipalTax: undefined,
      otherTax: undefined,
    },
    id: 0,
  },
  {
    productDetails: {
      productName: "Family Fun Day Pass",
      productType: "Festival",
      productCategory: "Entertainment",
      productSubCategory: "Family",
      productSubTitle: "Unlimited rides and activities for the whole family",
      img: Entertainment,
    },
    rulesAndTimeline: {
      minOrder: "1",
      maxOrder: "6",
      access: "All Rides and Activities",
      scan: "Barcode",
      salesStartDate: "2024-10-01",
      salesEndDate: "2024-11-30",
    },
    inclusion: {
      inclusionList: ["1", "22", "1111"],
    },
    pricing: {
      netSalesPrice: 100,
      transactionCurrency: "AED",
      vatTax: undefined,
      entertainmentTax: undefined,
      municipalTax: undefined,
      otherTax: undefined,
    },
    id: 0,
  },
  {
    productDetails: {
      productName: "Comedy Night Premium Seating",
      productType: "Comedy",
      productCategory: "Entertainment",
      productSubCategory: "Comedy",
      productSubTitle: "Premium seats with complimentary drinks",
      img: Entertainment,
    },
    rulesAndTimeline: {
      minOrder: "1",
      maxOrder: "4",
      access: "Premium Seating, Complimentary Drinks",
      scan: "QR Code",
      salesStartDate: "2024-10-15",
      salesEndDate: "2024-11-15",
    },
    inclusion: {
      inclusionList: [],
    },
    pricing: {
      netSalesPrice: 100,
      transactionCurrency: "AED",
      vatTax: undefined,
      entertainmentTax: undefined,
      municipalTax: undefined,
      otherTax: undefined,
    },
    id: 0,
  },
  {
    productDetails: {
      productName: "Theatre Show Deluxe Package",
      productType: "Theatre",
      productCategory: "Entertainment",
      productSubCategory: "Drama",
      productSubTitle: "Deluxe seating with access to the pre-show lounge",
      img: Entertainment,
    },
    rulesAndTimeline: {
      minOrder: "1",
      maxOrder: "4",
      access: "Deluxe Seating, Pre-show Lounge",
      scan: "Barcode",
      salesStartDate: "2024-11-01",
      salesEndDate: "2024-12-01",
    },
    inclusion: {
      inclusionList: [],
    },
    pricing: {
      netSalesPrice: 100,
      transactionCurrency: "AED",
      vatTax: undefined,
      entertainmentTax: undefined,
      municipalTax: undefined,
      otherTax: undefined,
    },
    id: 0,
  },
];

export const culturalPricingDetailsData: IPricingDetailsProps[] = [
  {
    productDetails: {
      productName: "Traditional Art Exhibition Pass",
      productType: "Exhibition",
      productCategory: "Cultural",
      productSubCategory: "Art",
      productSubTitle:
        "Access to exclusive traditional art pieces and guided tours",
      img: Owl,
    },
    rulesAndTimeline: {
      minOrder: "1",
      maxOrder: "4",
      access: "Art Gallery Access, Guided Tour",
      scan: "QR Code",
      salesStartDate: "2024-09-20",
      salesEndDate: "2024-10-15",
    },
    inclusion: {
      inclusionList: [],
    },
    pricing: {
      netSalesPrice: 100,
      transactionCurrency: "AED",
      vatTax: undefined,
      entertainmentTax: undefined,
      municipalTax: undefined,
      otherTax: undefined,
    },
    id: 0,
  },
  {
    productDetails: {
      productName: "Cultural Heritage Festival Ticket",
      productType: "Festival",
      productCategory: "Cultural",
      productSubCategory: "Heritage",
      productSubTitle: "Experience traditional music, dance, and food",
      img: Owl,
    },
    rulesAndTimeline: {
      minOrder: "1",
      maxOrder: "6",
      access: "Festival Grounds, All Activities",
      scan: "Barcode",
      salesStartDate: "2024-10-05",
      salesEndDate: "2024-11-01",
    },
    inclusion: {
      inclusionList: [],
    },
    pricing: {
      netSalesPrice: 100,
      transactionCurrency: "AED",
      vatTax: undefined,
      entertainmentTax: undefined,
      municipalTax: undefined,
      otherTax: undefined,
    },
    id: 0,
  },
  {
    productDetails: {
      productName: "Arabic Music Night Ticket",
      productType: "Concert",
      productCategory: "Cultural",
      productSubCategory: "Music",
      productSubTitle: "Live performance of traditional Arabic music",
      img: Owl,
    },
    rulesAndTimeline: {
      minOrder: "1",
      maxOrder: "4",
      access: "Concert Hall Seating",
      scan: "QR Code",
      salesStartDate: "2024-11-01",
      salesEndDate: "2024-12-01",
    },
    inclusion: {
      inclusionList: [],
    },
    pricing: {
      netSalesPrice: 100,
      transactionCurrency: "AED",
      vatTax: undefined,
      entertainmentTax: undefined,
      municipalTax: undefined,
      otherTax: undefined,
    },
    id: 0,
  },
  {
    productDetails: {
      productName: "Historical Documentary Screening Pass",
      productType: "Screening",
      productCategory: "Cultural",
      productSubCategory: "Documentary",
      productSubTitle: "Screening of historical documentaries with Q&A session",
      img: Owl,
    },
    rulesAndTimeline: {
      minOrder: "1",
      maxOrder: "5",
      access: "Screening Room, Q&A Session",
      scan: "Barcode",
      salesStartDate: "2024-12-01",
      salesEndDate: "2024-12-15",
    },
    inclusion: {
      inclusionList: [],
    },
    pricing: {
      netSalesPrice: 100,
      transactionCurrency: "AED",
      vatTax: undefined,
      entertainmentTax: undefined,
      municipalTax: undefined,
      otherTax: undefined,
    },
    id: 0,
  },
];
export const businessPricingDetailsData: IPricingDetailsProps[] = [
  {
    productDetails: {
      productName: "Executive Leadership Conference",
      productType: "Pass",
      productCategory: "Business",
      productSubCategory: "Leadership",
      productSubTitle:
        "Insights from top industry leaders and networking opportunities",
      img: Business,
    },
    rulesAndTimeline: {
      minOrder: "1",
      maxOrder: "5",
      access: "Conference Sessions, Networking Lunch",
      scan: "QR Code",
      salesStartDate: "2024-09-15",
      salesEndDate: "2024-10-30",
    },
    inclusion: {
      inclusionList: [],
    },
    pricing: {
      netSalesPrice: 100,
      transactionCurrency: "AED",
      vatTax: undefined,
      entertainmentTax: undefined,
      municipalTax: undefined,
      otherTax: undefined,
    },
    id: 0,
  },
  {
    productDetails: {
      productName: "Startup Networking Mixer",
      productType: "Networking",
      productCategory: "Business",
      productSubCategory: "Networking",
      productSubTitle: "Connect with fellow entrepreneurs and investors",
      img: Business,
    },
    rulesAndTimeline: {
      minOrder: "1",
      maxOrder: "3",
      access: "Networking Event, Drinks and Snacks",
      scan: "Barcode",
      salesStartDate: "2024-10-01",
      salesEndDate: "2024-11-15",
    },
    inclusion: {
      inclusionList: ["1", "22", "1111"],
    },
    pricing: {
      netSalesPrice: 100,
      transactionCurrency: "AED",
      vatTax: undefined,
      entertainmentTax: undefined,
      municipalTax: undefined,
      otherTax: undefined,
    },
    id: 0,
  },
  {
    productDetails: {
      productName: "Corporate Training Workshop",
      productType: "Workshop",
      productCategory: "Business",
      productSubCategory: "Training",
      productSubTitle: "Hands-on training on the latest business practices",
      img: Business,
    },
    rulesAndTimeline: {
      minOrder: "1",
      maxOrder: "10",
      access: "Training Materials, Lunch Included",
      scan: "QR Code",
      salesStartDate: "2024-11-01",
      salesEndDate: "2024-12-01",
    },
    inclusion: {
      inclusionList: ["One"],
    },
    pricing: {
      netSalesPrice: 100,
      transactionCurrency: "AED",
      vatTax: undefined,
      entertainmentTax: undefined,
      municipalTax: undefined,
      otherTax: undefined,
    },
    id: 0,
  },
  {
    productDetails: {
      productName: "Annual Business Gala Dinner",
      productType: "Gala Dinner",
      productCategory: "Business",
      productSubCategory: "Event",
      productSubTitle: "Elegant dinner with awards and entertainment",
      img: Business,
    },
    rulesAndTimeline: {
      minOrder: "1",
      maxOrder: "8",
      access: "Dinner, Awards Ceremony, Entertainment",
      scan: "Barcode",
      salesStartDate: "2024-12-01",
      salesEndDate: "2024-12-20",
    },
    inclusion: {
      inclusionList: ["One"],
    },
    pricing: {
      netSalesPrice: 100,
      transactionCurrency: "AED",
      vatTax: undefined,
      entertainmentTax: undefined,
      municipalTax: undefined,
      otherTax: undefined,
    },
    id: 0,
  },
];
