import { IMonitoringProps } from "./types";

export const monitoringData: IMonitoringProps[] = [
  {
    product: "Event A",
    scanned: 120,
    remaining: 80,
    total: 200,
    progress: 60,
    status: "In Progress",
  },
  {
    product: "Event B",
    scanned: 50,
    remaining: 150,
    total: 200,
    progress: 25,
    status: "Pending",
  },
  {
    product: "Event C",
    scanned: 200,
    remaining: 0,
    total: 200,
    progress: 100,
    status: "Completed",
  },
  {
    product: "Event D",
    scanned: 75,
    remaining: 125,
    total: 200,
    progress: 37.5,
    status: "In Progress",
  },
  {
    product: "Event E",
    scanned: 180,
    remaining: 20,
    total: 200,
    progress: 90,
    status: "Almost Done",
  },
  {
    product: "Event F",
    scanned: 40,
    remaining: 160,
    total: 200,
    progress: 20,
    status: "Pending",
  },
  {
    product: "Event G",
    scanned: 95,
    remaining: 105,
    total: 200,
    progress: 47.5,
    status: "In Progress",
  },
  {
    product: "Event H",
    scanned: 10,
    remaining: 190,
    total: 200,
    progress: 5,
    status: "Pending",
  },
  {
    product: "Event I",
    scanned: 190,
    remaining: 10,
    total: 200,
    progress: 95,
    status: "Almost Done",
  },
  {
    product: "Event J",
    scanned: 30,
    remaining: 170,
    total: 200,
    progress: 15,
    status: "Pending",
  },
  {
    product: "Event K",
    scanned: 110,
    remaining: 90,
    total: 200,
    progress: 55,
    status: "In Progress",
  },
  {
    product: "Event L",
    scanned: 50,
    remaining: 150,
    total: 200,
    progress: 25,
    status: "Pending",
  },
  {
    product: "Event M",
    scanned: 150,
    remaining: 50,
    total: 200,
    progress: 75,
    status: "Almost Done",
  },
  {
    product: "Event N",
    scanned: 5,
    remaining: 195,
    total: 200,
    progress: 2.5,
    status: "Pending",
  },
  {
    product: "Event O",
    scanned: 175,
    remaining: 25,
    total: 200,
    progress: 87.5,
    status: "In Progress",
  },
  {
    product: "Event P",
    scanned: 80,
    remaining: 120,
    total: 200,
    progress: 40,
    status: "In Progress",
  },
  {
    product: "Event Q",
    scanned: 95,
    remaining: 105,
    total: 200,
    progress: 47.5,
    status: "In Progress",
  },
  {
    product: "Event R",
    scanned: 200,
    remaining: 0,
    total: 200,
    progress: 100,
    status: "Completed",
  },
  {
    product: "Event S",
    scanned: 160,
    remaining: 40,
    total: 200,
    progress: 80,
    status: "Almost Done",
  },
  {
    product: "Event T",
    scanned: 20,
    remaining: 180,
    total: 200,
    progress: 10,
    status: "Pending",
  },
];
