import { IMonitoringProps } from "./types";

export const monitoringData: IMonitoringProps[] = [
  {
    product: "Silver Ticket",
    scanned: 120,
    remaining: 80,
    total: 200,
    progress: 60,
    status: "In Progress",
  },
  {
    product: "Gold Ticket",
    scanned: 50,
    remaining: 150,
    total: 200,
    progress: 25,
    status: "Pending",
  },
  {
    product: "Platinum Ticket",
    scanned: 200,
    remaining: 0,
    total: 200,
    progress: 100,
    status: "Completed",
  },
  {
    product: "Diamond Ticket",
    scanned: 75,
    remaining: 125,
    total: 200,
    progress: 37.5,
    status: "In Progress",
  },
  {
    product: "VIP Ticket",
    scanned: 180,
    remaining: 20,
    total: 200,
    progress: 90,
    status: "Almost Done",
  },
  {
    product: "Standard Ticket",
    scanned: 40,
    remaining: 160,
    total: 200,
    progress: 20,
    status: "Pending",
  },
  {
    product: "Exclusive Pass",
    scanned: 95,
    remaining: 105,
    total: 200,
    progress: 47.5,
    status: "In Progress",
  },
  {
    product: "Early Bird Ticket",
    scanned: 10,
    remaining: 190,
    total: 200,
    progress: 5,
    status: "Pending",
  },
  {
    product: "Front Row Ticket",
    scanned: 190,
    remaining: 10,
    total: 200,
    progress: 95,
    status: "Almost Done",
  },
  {
    product: "Backstage Pass",
    scanned: 30,
    remaining: 170,
    total: 200,
    progress: 15,
    status: "Pending",
  },
  {
    product: "Lounge Ticket",
    scanned: 110,
    remaining: 90,
    total: 200,
    progress: 55,
    status: "In Progress",
  },
  {
    product: "Group Ticket",
    scanned: 50,
    remaining: 150,
    total: 200,
    progress: 25,
    status: "Pending",
  },
  {
    product: "Family Pack Ticket",
    scanned: 150,
    remaining: 50,
    total: 200,
    progress: 75,
    status: "Almost Done",
  },
  {
    product: "Promo Ticket",
    scanned: 5,
    remaining: 195,
    total: 200,
    progress: 2.5,
    status: "Pending",
  },
  {
    product: "Season Pass",
    scanned: 175,
    remaining: 25,
    total: 200,
    progress: 87.5,
    status: "In Progress",
  },
  {
    product: "Corporate Ticket",
    scanned: 80,
    remaining: 120,
    total: 200,
    progress: 40,
    status: "In Progress",
  },
  {
    product: "Ultimate Experience Pass",
    scanned: 95,
    remaining: 105,
    total: 200,
    progress: 47.5,
    status: "In Progress",
  },
  {
    product: "Premium Ticket",
    scanned: 200,
    remaining: 0,
    total: 200,
    progress: 100,
    status: "Completed",
  },
  {
    product: "Super VIP Ticket",
    scanned: 160,
    remaining: 40,
    total: 200,
    progress: 80,
    status: "Almost Done",
  },
  {
    product: "Budget Ticket",
    scanned: 20,
    remaining: 180,
    total: 200,
    progress: 10,
    status: "Pending",
  },
];
