import { IPromotionsImportCampaigns } from "./import-type";

export const promotionsImportCampaignsData: IPromotionsImportCampaigns[] = [
  {
    type: "Percentage",
    campaignsName: "Summer Sale",
    startDate: "2025-01-01T00:00:00Z",
    expiryDate: "2025-03-01T23:59:59Z",
    discount: 20,
    discountValue: "20%",
    numberOfCodes: 10,
    usagePerCode: "unlimited",
    organization: "Company A",
    issuedBy: "Admin",
    emailAddress: "admin@companya.com",
    sources: "Generated",
    application: "On Order",
    unit: "10",
    codesAndUsage: Array.from({ length: 5 }, (_, i) => ({
      code: `SUMMER${i + 1}`,
      discount: "25%",
      unit: '100',
    })),
  },
  {
    type: "Flat",
    campaignsName: "Winter Deal",
    startDate: "2025-02-01T00:00:00Z",
    expiryDate: "2025-04-01T23:59:59Z",
    discount: 15,
    discountValue: "$15",
    numberOfCodes: 7,
    application: "On Order",
    usagePerCode: "limited",
    organization: "Company B",
    issuedBy: "Manager",
    unit: "10",
    emailAddress: "manager@companyb.com",
    sources: "Imported",
    codesAndUsage: Array.from({ length: 5 }, (_, i) => ({
      code: `WINTER${i + 1}`,
      discount: "50%",
      unit: '150',
    })),
  },
  {
    type: "Buy One Get One",
    campaignsName: "BOGO Special",
    startDate: "2025-03-01T00:00:00Z",
    expiryDate: "2025-05-01T23:59:59Z",
    application: "On Order",
    discount: 50,
    discountValue: "50%",
    numberOfCodes: 8,
    usagePerCode: "unlimited",
    unit: "10",
    organization: "Company C",
    issuedBy: "Team Lead",
    emailAddress: "teamlead@companyc.com",
    sources: "Generated",
    codesAndUsage: Array.from({ length: 5 }, (_, i) => ({
      code: `BOGO${i + 1}`,
      discount: "35%",
      unit: '50',
    })),
  },
];
